### ISSUE TITLE
🐛 [BUG]: Settings nodes and edges via v-model broken since 1.16.0

### ISSUE THREAD

**Issue by rogeru** [bcakmakoglu/vue-flow#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

My app allows the user to create a flow, then save it which saves the nodes and edges based on `elements` which is defined as v-model of VueFlow. On page reload the v-model variable `elements` is set to the saved array.

Prior to 1.16.0 this was working fine.
Since 1.16.0 only the nodes are drawn. The edges are missing. Looking at the vue dev tools, the edges are in the elements. But looking at the rendered html, the container for the edges (class vue-flow__edges) is empty.

### Expected Behavior

Setting v-model of VueFlow with nodes and edges should render the edges as well, not just the nodes.
Was working fine in 1.15.5 .

Are we supposed to use addEdges instead post 1.15.5?

### Steps To Reproduce

If needed I could create a sandbox replicating this, but as stated above this is pretty straight forward.

**Comment by bcakmakoglu** [comment]
You'll have to provide a proper reproduction for this issue as you can very well see on the docs page that v-model works absolutely fine for nodes and edges.

Just saying "it's straight forward" isn't helping either 😉 
It doesn't work *for you* - so please properly demonstrate the issue with a reproduction so I can actually help and debug, otherwise I can't do much.

**Comment by bcakmakoglu** [comment]
[Here's a template for you to get started.](https://codesandbox.io/p/sandbox/competent-colden-h3gv3r?file=%2Findex.html%3A1%2C1)

**Comment by rogeru** [comment]
In trying to reproduce I found the issue on my side. My code in `isValidConnection` has a bug and therefore prevented the edges to be drawn. And of course since `isValidConnection` was only added in 1.16.0, going back to 1.15.x does not execute the function.

My apologies. Keep up the good work @bcakmakoglu
