### ISSUE TITLE
🐛 [BUG]: <Vue-cli4.x error>

### ISSUE THREAD

**Issue by io-o** [bcakmakoglu/vue-flow#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Hi, I followed the official documentation to install and use the package, but I encountered an error. Here's the error message:
<img width="1163" alt="image" src="https://github.com/bcakmakoglu/vue-flow/assets/22197685/e7e789a7-9c94-4677-b680-835f99288e28">

"vue": "^3.2.39"
"@vue-flow/core": "^1.20.2"
"@vue/cli": "~4.5.0"

How can I configure the loader?

thx

### Expected Behavior

How to solve？

**Comment by bcakmakoglu** [comment]
[This discussion might help you.](https://github.com/bcakmakoglu/vue-flow/discussions/851)

**Comment by io-o** [comment]
Thx,  It's effective
