### ISSUE TITLE
🐛 [BUG]: <my node toolbar is don't show >

### ISSUE THREAD

**Issue by Gemini-0529** [bcakmakoglu/vue-flow#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

> index.vue

```
<VueFlow snap-to-grid>
        <MiniMap pannable zoomable/>
        <Controls />
        <template #node-custom="nodeProps">
          <CustomNode :data="nodeProps.data" :label="nodeProps.label" />
        </template>
        <Background/>
      </VueFlow>
```
> customNode.vue

```
<script lang="ts" setup>
import { Handle, Position } from '@vue-flow/core'
import { NodeToolbar } from '@vue-flow/node-toolbar'
import { onMounted } from 'vue'

interface NodeData {
  toolbarVisible: boolean
  toolbarPosition: Position
}

interface Props {
  data: NodeData
  label: string
}
const props = defineProps<Props>()
onMounted(() => {
  console.log(props.data);
})
</script>

<template>
  <NodeToolbar :is-visible="data.toolbarVisible" :position="data.toolbarPosition">
    <button>delete</button>
    <button>copy</button>
    <button>expand</button>
  </NodeToolbar>

  <div :style="{ padding: '10px 20px' }">
    {{ label }}
  </div>

  <Handle type="target" :position="Position.Left" />
  <Handle type="source" :position="Position.Right" />
</template>
```
node toolbar is don't show

### Expected Behavior

must use v-model="elements" ?

**Comment by bcakmakoglu** [comment]
Please provide a proper description for your issue and a reproduction otherwise it's a bit difficult to even know what your problem is, what you tried and what isn't working for you.
[Here's a template for a sandbox.](https://codesandbox.io/p/sandbox/eloquent-grass-z2m688?file=%2Findex.html%3A1%2C1)

**Comment by Gemini-0529** [comment]
Thanks to the author for reply! Maybe I need to set the node type to toolbar.

**Comment by bcakmakoglu** [comment]
You don't need to set your node type as `toolbar` but `custom` seeing as you're using `<template #node-custom="nodeProps">` (you defined the slot for a node with the type `custom` not `node-toolbar`)

[Have you properly followed this example?](https://vueflow.dev/examples/nodes/node-toolbar.html)

The example does use `toolbar` as a custom node type, but the type really depends on what you're using.
If you set the node type to `type: 'custom'` then the slot should use `node-custom` etc.

**Comment by Gemini-0529** [comment]
I see. I see. If I want different types of nodes to display toolbar, how do I configure it?
> node
```
[
{
    id: "1",
    label: "Node 1",
    type: 'input',
    position: { x: 105, y: 60 },
    class: "rootNodeClass",
    style: defaultNodeStyle,
    data: {
      toolbarPosition: Position.Top,
    },
  },
{
    id: "2",
    label: "Node 2",
    type: "toolbar",
    position: { x: 270, y: 60 },
    style: { backgroundColor: "green" },
    data: {
      toolbarPosition: Position.Top,
    },
  },
]
```

**Comment by bcakmakoglu** [comment]
If you want a toolbar for default node types, create a node toolbar outside of the node components, similar to this

```vue
<NodeToolbar nodeId={selectedNodeIds} isVisible={isVisible}>
  <button>multi selection toolbar</button>
</NodeToolbar>
```

Otherwise just do what is shown in the example - create a custom node and add the toolbar inside of the node component.

**Comment by Gemini-0529** [comment]
I get it, thanks.
