### ISSUE TITLE
🐛 [BUG]: nodes are not fixed on their positions during pinch-zoom on a touchscreen

### ISSUE THREAD

**Issue by heaven-born** [bcakmakoglu/vue-flow#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When I use my phone I expect to use my fingers for zooming this way:  touch the video with two fingers and move them away from one another or in the opposite direction. The zoom is working this way, but there is a side effect: when one of my fingers touches one of the nodes, the node is also moving along with the finger.  

### Expected Behavior

I expect the vueflow to detect the pinch-zoom start and fix all nodes in their places until the zoom is complete. 

### Steps To Reproduce

1. On a phone or another touch screen place one of your fingers on a node and another one on a free area. 
2. Perform a pinch-zoom and observe that the node is moving.

**Comment by bcakmakoglu** [comment]
Thanks for the report, I'll see what I can do about this :)
