### ISSUE TITLE
🐛 [BUG]: Edge Validation doesn't toggle "connecting" and "isValid" classes

### ISSUE THREAD

**Issue by GalacticWeb** [bcakmakoglu/vue-flow#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

The handle components should recieve a "connecting" css class, currently this css class is not toggled. Therefore visual feedback is not possible on an edge "isValidConnection" function. 

It should happen in this line: 
https://github.com/bcakmakoglu/vue-flow/blob/ab3bb71b0a28249da71d7bc5f5d7b39691b089d0/packages/core/src/composables/useHandle.ts#L194``

### Expected Behavior

With this useHandle refactor it works: 

https://vue-flow-docs-git-refactor-use-handle-bcakmakoglu.vercel.app/examples/edges/validation.html

### Steps To Reproduce

This official example has the same problem: 

https://vueflow.dev/examples/edges/validation.html

**Comment by bcakmakoglu** [comment]
Thanks for reporting 👍 
Will be fixed in `1.21.2`

**Comment by bcakmakoglu** [comment]
Fix released with `1.21.2`
