### ISSUE TITLE
🐛 [BUG]: `fitView` can produce an infinitely large (invalid) viewport

### ISSUE THREAD

**Issue by snoozbuster** [bcakmakoglu/vue-flow#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

In rare cases, calling `fitView` can produce a viewport which has `NaN` for its `x` and `y` values.

### Expected Behavior

`fitView` should no-op in these cases.

### Steps To Reproduce

I'm not sure what a minimal in-browser reproduction of this would look like - I have a very complex reproduction in my app which I've debugged but cannot share, but I can provide an in-depth explanation of the issue, rough steps by which I caused this issue in my app, and a suggestion for a unit test which would reproduce the issue.

In [`useViewport#fitView()`](https://github.com/bcakmakoglu/vue-flow/blob/f28a4e03b9ca03c0e2f219b65a7658f784d49567/packages/core/src/composables/useViewport.ts#L92), there is a check at the top of the function to no-op if `nodes.length` is 0. However, the next line executes a filter on the node list to produce a variable called `nodesToFit`. This array can filter out all candidate nodes and produce an empty list - the way this happens in my app is that all the nodes in the graph state are uninitialized (do not have a width/height). The end result is that [`getRectOfNodes`](https://github.com/bcakmakoglu/vue-flow/blob/master/packages/core/src/utils/graph.ts#L315) returns an infinitely large box, and then `getTransformForBounds` returns an object with `{ x: NaN, Y: NaN }`. 

I think the bail-out check should be moved after the filter and modified to check `nodesToFit.length`, which would guarantee that the no-op works correctly if there are no nodes to fit for.

The rough way this is produced in my application involves the following steps:

- I add one node to the graph when my root VueFlow component mounts.
- In that component, I set up an `onPaneReady(() => { initializeNodes(); fitView() })` callback.
- `initializeNodes` adds a node to the graph
- in that node's component's onMounted, it triggers a watcher which removes the one node added in the first step
- `fitView` runs. the only node in the graph is one which is uninitialized. The graph state has nodes, but they are all filtered out of `nodesToFit`. 
- Kaboom

A unit test of `fitView` which tests that it does not produce NaNs when the graph state contains only uninitialized nodes would be sufficient both to reproduce this issue and to verify that it is fixed.

**Comment by bcakmakoglu** [comment]
Thanks for the report, I'll give it a look.

Though I am *very* confused about the steps you described, what even are you trying to achieve there?
You add a node, which adds another node, which removes the first node and calls fit view, which then causes an issue because the 2nd node isn't initialized yet?

What would even be the outcome *if* fitView didn't throw an error? Nothing?
One node?

Would be nice if you could describe the use-case a bit more in detail and what the outcome is even supposed to be because to me it sounds like you're trying your hardest to produce errors 😂

**Comment by bcakmakoglu** [comment]
Btw, this will be fixed in `1.21.3` and thanks again for the report and thorough analysis, very much appreciated 👍

**Comment by bcakmakoglu** [comment]
Fix released in `1.21.3`

**Comment by snoozbuster** [comment]
>What would even be the outcome if fitView didn't throw an error? Nothing?
Yep, nothing - same as if you called it with no nodes in the state.

>Would be nice if you could describe the use-case a bit more in detail and what the outcome is even supposed to be
The outcome is supposed to be that the library continues to work. I don't have a use case here - I am describing emergent, unintentional behavior that my app has produced, quite by accident, by virtue of its architecture and the decisions of other developers. To be a little more specific, so that you can understand how we got here a little better:

We are rendering some first-time use hints into the graph in my application (eg, a "drop nodes here" sort of target), which is automatically removed when the first change to the graph is made. The nodes themselves render custom components which are generally responsible for managing user-initiated updates to the nodes' settings. Up until I discovered this bug, these nodes always mounted with the correct initial/default state, so there was no need to trigger any updates to the graph on mount. What ended up happening in this case is that one of my other team members decided to effect a change to the graph on the first mount of a new node type they were adding (to fix some missing default data), which triggered the "remove the first-time hints" code immediately during the initial mount of the graph. Due to the way the application was built, this ultimately caused the described issue. We fixed the causes of this in our application as well, as it was never intended to trigger the removal of the hints this early or in this way, but I wanted to also surface the issue here as based on my debugging and the way the library code was written, it seemed that this possibility was known and guarded against, but the guard did not work properly in all cases.
