### ISSUE TITLE
🐛 [BUG]: Uncaught (in promise) TypeError: Illegal invocation

### ISSUE THREAD

**Issue by anhnhoktvn** [bcakmakoglu/vue-flow#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

![image](https://github.com/bcakmakoglu/vue-flow/assets/2435820/8032ac4f-bc83-4ab2-97a8-1e2cfbd3415e)

### Expected Behavior

No error

### Steps To Reproduce

1. https://vueflow.dev/examples/
2. Choose an example and find the preview area.
3. Click on a node
4. Press Esc
5. Open devtool to see the error

### Anything else?

There are 2 error in the log
```
Cannot read properties of null (reading 'includes')
```
and
```
Uncaught (in promise) TypeError: Illegal invocation
```
And I'm reporting the second
The 2nd error happens on my side too but I think it's simpler to use the main site to reproduce the error

**Comment by bcakmakoglu** [comment]
Thanks for the report, will be fixed in `1.22.1`
