### ISSUE TITLE
🐛 [BUG]:  onNodeDragStop/Start should not be triggered on click.

### ISSUE THREAD

**Issue by heaven-born** [bcakmakoglu/vue-flow#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Currently `onNodeDragStart` is triggered by any click on the node. 

### Expected Behavior

`onNodeDragStart` should be triggered only if some coordinate change is detected. 

In my case, the client sends coordinate updates to the server on every node move event. Triggering  `onNodeDragStart` on click causes redundant requests to be sent if I also have a double-click listener configured on the node. 

### Steps To Reproduce

 Example: https://codesandbox.io/p/sandbox/async-sun-xcwp35?file=%2Fsrc%2FApp.vue%3A23%2C16

 Clicking on the node triggers `onNodeDragStart` event.

**Comment by bcakmakoglu** [comment]
This is not a bug. A drag is registered on mousedown and mouseup, which is the same as a click, that's why it will always fire this event as well.
The way around this is to track the dragging state of your node and compare it in a click.

**Comment by heaven-born** [comment]
Shouldn't the events be called  `onNodeMouseDown` and  `onNodeMouseUp` if they don't detect the dragging?

**Comment by heaven-born** [comment]
or `onNodeDraggingAreaMouseDown` and `onNodeDraggingAreaMouseUp`
