### ISSUE TITLE
🐛 [BUG]: NodeReziser does not respect minWidth and minHeight when new node is added

### ISSUE THREAD

**Issue by linspw** [bcakmakoglu/vue-flow#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Hello everything is fine?

Again I want to thank you for this incredible work!

I want to report a "Bug/Feature"

When adding a new node the minimum resizing is not calculated.

However, as the width and height are not calculated, it allows the size to self-adjust when editing the content (which is very good for inline editing)

Thanks in advance for your attention, thank you!

### Expected Behavior

Possibilities I thought of:
- Update the size if it is smaller than the minimum size when adding a new node
- When editing content somehow triggers automatic resize
- Or use minWidth and minHeight in css instead of height for resizing cases

### Steps To Reproduce

- Add new node with size lower than minWidth or minHeight

### Anything else?

[Gravação de tela de 03-08-2023 11:13:03.webm](https://github.com/bcakmakoglu/vue-flow/assets/43552865/bc843c59-4c62-4433-9d4c-6653c33300bd)
[Gravação de tela de 03-08-2023 11:09:38.webm](https://github.com/bcakmakoglu/vue-flow/assets/43552865/4530d86b-b7cc-488b-9411-38688d643eec)

**Comment by bcakmakoglu** [comment]
Thanks for reporting, I'll take a look and see what I can do.

**Comment by bcakmakoglu** [comment]
Should be fixed with `@vue-flow/node-resizer@1.3.4`
