### ISSUE TITLE
Floating edges missing

### ISSUE THREAD

**Issue by Xsmael** [bcakmakoglu/vue-flow#1074]
What happened to floating edges ?  I can't see it in the docs or examples and all links reated to it show 404 Page 
I really needed this feature, but i can't find it no where not even on the git repo.

Thanks

_Originally posted by @Xsmael in https://github.com/bcakmakoglu/vue-flow/discussions/46#discussioncomment-6649886_

**Comment by bcakmakoglu** [comment]
Check the discussion again, I added a link to the example in the repo.
