### ISSUE TITLE
🐛 [BUG]:  class 'nodrag' in NodeToolbar does not work

### ISSUE THREAD

**Issue by 284668461** [bcakmakoglu/vue-flow#1095]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Using the class 'nodrag' in NodeToolbar does not work.

`
 <div class="inputNode node" >

                <div class="nodeLabel">input:</div>
                <input type="number" class="nodrag" value="10"></input>

                <NodeToolbar position={Position.Right} isVisible={data.toolbarVisible}>
                    <input type="number" class="nodrag"></input>
                </NodeToolbar>
            </div >
`

### Expected Behavior

Work like you're in custom Node

### Anything else?

https://github.com/bcakmakoglu/vue-flow/assets/38812759/85035fb6-0766-45cf-9f91-2fcc22486d24

**Comment by bcakmakoglu** [comment]
What would you expect nodrag to do here?🤔
Nodrag is supposed to prevent a node from being dragged if a specific element is targeted but a Toolbar doesn’t trigger drag anyway so this “bug” report doesn’t really make sense to me here.

**Comment by bcakmakoglu** [comment]
@284668461 ping - can you respond to me previous question? :)

**Comment by bcakmakoglu** [comment]
Closing due to a lack of information here, please re-open if necessary.
