### ISSUE TITLE
🐛 [BUG]: Dynamically adding child nodes with existing relation

### ISSUE THREAD

**Issue by harshaktg** [bcakmakoglu/vue-flow#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I am trying to add a child node dynamically in the graph. I already have an edge which has connection from that particular child node to another node. Once the child node is successfully added on the graph, the edge is not drawn though the edge object is still present. 

[Here is the sandbox link](https://codesandbox.io/p/sandbox/cold-bush-psxhdr?file=/src/App.vue:15,62)

### Expected Behavior

It should have drawn the edge when the node is dynamically added

**Comment by bcakmakoglu** [comment]
Edges *always* need to reference existing nodes
You can’t just „create“ an edge and add the nodes for it afterwards, if that’s what you’re doing.
