### ISSUE TITLE
🐛 [BUG]: <title>Pattern confusion

### ISSUE THREAD

**Issue by gamerssong** [bcakmakoglu/vue-flow#1104]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Sample and local import style confusion[](url)

### Expected Behavior

![1695622895479](https://github.com/bcakmakoglu/vue-flow/assets/42994268/fcfa1e55-a4b5-42ec-9e21-d8302de466b0)

**Comment by bcakmakoglu** [comment]
What's this issue about? Please provide a proper and clear description as this issue provides 0 info.

**Comment by gamerssong** [comment]
I see it's repaired now, So quickly！
