### ISSUE TITLE
🐛 [BUG]: VueFlow doesn't make connections in v.1.22.3

### ISSUE THREAD

**Issue by TagaevRenat** [bcakmakoglu/vue-flow#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I have updated vueflow/core from 1.15.2 to 1.22.3, and at 1.22.3 connections aren't created :(
Vueflow doesn't emit "connect" event also. "connectStart" and "connectEnd" are still avalible. I'm using "isValidTargetPos" to validate connection, and this function doesn't trigger.

If I change vueflow/core version to 1.15.2 everything is fine, without any other changes. Perhaps the problem occurred in earlier versions.

### Expected Behavior

Vueflow should create connections and trigger validation function, if it exist

### Steps To Reproduce

1. Update vueflow/core to 1.22.3
2. Try to create connection :)

**Comment by bcakmakoglu** [comment]
You'll have to provide a proper reproduction for this issue as creating connections *does work* (as seen in any example on the docs + I use Vue Flow in a project as well and have 0 issues creating edges).

[Here's a template that you can use.](https://codesandbox.io/p/sandbox/holy-sea-85pmnc?file=%2Findex.html%3A1%2C1)

**Comment by TagaevRenat** [comment]
I found out that my problem was in 1.17.5 version, cause behaviour of handle component was changed (attr connectable).
Thank you for fast feedback.
