### ISSUE TITLE
An issue to say thank you

### ISSUE THREAD

**Issue by SirMishaa** [bcakmakoglu/vue-flow#113]
I started using this library a few days ago and it is wonderful.

I wanted to say thank you, really, this contribution to the Vue ecosystem is wonderful. 

Thank you very much to you and to the contributors for this work, it's very enjoyable. ❤️

**Comment by bcakmakoglu** [comment]
Thank you very much for your kind words 😄 
This keeps me motivated updating Vue Flow further, so your "issue" is very much appreciated
