### ISSUE TITLE
🐛 [BUG]: The Example page on the official website is down

### ISSUE THREAD

**Issue by ZzTaidhm** [bcakmakoglu/vue-flow#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

broke up 

### Expected Behavior

broke up

**Comment by juan-morales** [comment]
Also experiencing this

**Comment by bcakmakoglu** [comment]
Examples should work again, please try it again (make sure you're not caching the site though 😉)
