### ISSUE TITLE
🐛 [BUG]: Node Toolbar and Node Resizer examples not working

### ISSUE THREAD

**Issue by bcakmakoglu** [bcakmakoglu/vue-flow#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

The examples aren't working in the Repl for some reason, though the component itself does work.

### Expected Behavior

The examples should work.

**Comment by vntalking** [comment]
I have same issue

**Comment by cn-code-bear** [comment]
I have same issue

**Comment by bcakmakoglu** [comment]
Fixed
