### ISSUE TITLE
🐛 [BUG]: change in documentation

### ISSUE THREAD

**Issue by leonardokatayama** [bcakmakoglu/vue-flow#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

In the documentation, the slot for locking and unlocking is referred to as control-interaction

### Expected Behavior

Change it to control-interactive, as looking at the code this is the correct name for the slot

**Comment by bcakmakoglu** [comment]
Thanks for the report, the typo is fixed 👍
