### ISSUE TITLE
🐛 [BUG]: 3 Handle for edge couldn't connect when i set sourceHandleId and targetHandleId

### ISSUE THREAD

**Issue by muktadira22** [bcakmakoglu/vue-flow#1223]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

![image](https://github.com/bcakmakoglu/vue-flow/assets/38875302/747caf68-9929-4fee-a0e4-b1cf99236172)

when i want to set edge from "Example-Insurance" from right handle, to top handle in "Example Dietitian" node, it's not work, here's my code for Nodes

```
 {
        id: "insurance",
        type: "custom",
        label: "Insurance",
        position: { x: 150, y: 250 },
        data: {
            icon: h(RiHandHeartFill, {
                fill: "#fff",
                class: "icon-size-20",
            }),
            iconBgColor: "purple",
            edgePositions: [
                { id: "top", position: Position.Top, type: "target" },
                { id: "bottom", position: Position.Bottom, type: "source" },
                { id: "right", position: Position.Right, type: "source" },
            ],
        },
    },
 {
        id: "dietitian",
        type: "custom",
        label: "Dietitian",
        position: { x: 590, y: 510 },
        data: {
            icon: h(RiHealthBookFill, {
                fill: "#fff",
                class: "icon-size-20",
            }),
            iconBgColor: "primary",
            edgePositions: [
                { id: "top", position: Position.Top, type: "target" },
            ],
        },
    },
```

and here's for my edge

```
 {
    id: "insurance-to-dietitian",
    source: "insurance",
    target: "dietitian",
    sourceHandleId: "right",
    targetHandleId: "top",
},
```

i'm using v-for for iteration the handle, and here's my code for NodesCustom

````
<template>
    <div
        class="monitoring-node d-flex flex-column align-items-center justify-content-center"
    >
    <h6 class="node-label">Example-{{ payload.label }}</h6>
    </div>

    <Handle
        v-for="edge in edgePositions"
        :type="edge.type"
        :position="edge.position"
        :id="edge.id"
        :connectable-end="false"
        :connectable-start="false"
    />
</template>
````

### Expected Behavior

and here's my expectation, thank you

![image](https://github.com/bcakmakoglu/vue-flow/assets/38875302/adf48a0a-551b-426c-9bea-63bcf57338dc)

**Comment by bcakmakoglu** [comment]
Are you sure your handle ids are *unique*?

You're most likely using non-unique handle ids which makes the lookup barely possible. Each handle has to have a *unique* id if you want to use multiple handles *on the same node* - if a node does not have multiple handles of the same type (source/target), you don't need an id.
Additionally, if you try to change the direction of your edges dynamically, *please read the relevant section of the docs for dynamic handles*: https://vueflow.dev/guide/node.html#working-with-dynamic-handle-positions-adding-handles-dynamically

**Comment by muktadira22** [comment]
for id in every node is unique, but every handle id  in every node is same, like in node a, we have handle id [right, left]. node b is same have id right, and left too, it's okay ? and i just realized for one node have 3 handle, top for target, bottom and right for source ? how can i handle it thank you

**Comment by bcakmakoglu** [comment]
Like I said, each handle has to have it's *own unique id*. Re-using `right`, `left` etc. isn't gonna yield the result you are expecting it to.

**Comment by bcakmakoglu** [comment]
Is this issue resolved? If not, please re-open it again
