### ISSUE TITLE
🐛 [BUG]: `isRect` returns false for rectangles positioned on the origin (or on an axis)

### ISSUE THREAD

**Issue by snoozbuster** [bcakmakoglu/vue-flow#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

`isRect` returns false for any rectangle with an x or y position of 0. 

### Expected Behavior

`isRect` should return true for all rectangles with valid x and y positions.

### Steps To Reproduce

The way I found this was to call `getIntersectingNodes` with a rect which happened to be aligned on the x-axis.

### Anything else?

https://github.com/bcakmakoglu/vue-flow/blob/master/packages/core/src/utils/graph.ts#L93 this check tests for truthiness of values, which does not work for x and y. (it's debatable whether or not it's appropriate for width and height, but if you want to assert that 0-area rectangles are not rectangles, then I guess this is acceptable behavior.)

A better check would be `typeof rect.x === 'number'`, but this also fails if you would like to exclude `NaN` and infinity. An ideal check would be `Number.isFinite(rect.x)`. Note that this is different from the bare `isFinite()`, which performs coercion.

**Comment by bcakmakoglu** [comment]
Will be fixed in `1.30.1`
