### ISSUE TITLE
dragndrop is not working

### ISSUE THREAD

**Issue by hurbanom** [bcakmakoglu/vue-flow#13]
I'll try to use dragndrop example, but I'm getting many errors

I'm testing the library with laravel-mix, and when I try to compile gives me this error:

![image](https://user-images.githubusercontent.com/13169697/144346356-861440ab-6d48-420d-9fbe-9e4d4cef3d7a.png)

And the method onDrop it isn't fire,

I hope somebody can help me!

Regards

**Comment by bcakmakoglu** [comment]
@hurbanom 
Are you using Vue3 with Laravel-Mix?
Also "FlowInstance" is a typescript interface - not an actual class to use.
If you're not using TypeScript you shouldn't be importing it.

**Comment by bcakmakoglu** [comment]
Closed this due to unresponsiveness.
