### ISSUE TITLE
🐛 [BUG]: multi-selection-key-code property error

### ISSUE THREAD

**Issue by bUxEE** [bcakmakoglu/vue-flow#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When setting a keycode for multi-selection-key-code and pressing on a keyboard key you get the following error in console:
```
Uncaught TypeError: currentFilter is not a function
    at vue-flow-core.mjs:3371:18
```

### Expected Behavior

Supposed to be able to select multiple node by clicking on the while keeping the keyboard key pressed whos keycode as been passed in the multi-selection-key-code param value

### Steps To Reproduce

1. add multi-selection-key-code property to VueFlow compoenent
2. press any key on keyboard

### Relevant log output

```shell
Uncaught TypeError: currentFilter is not a function
    at vue-flow-core.mjs:3371:18
```

**Comment by bcakmakoglu** [comment]
I can't reproduce this on the latest version.
What did you use as a keycode? I assume you've used an invalid value and that's why it errors.

This worked perfectly fine:
```vue
<VueFlow v-model="elements" multi-selection-key-code="Meta" />

<!-- or -->
<VueFlow v-model="elements" multi-selection-key-code="Meta+A" />

<!-- or -->
<VueFlow v-model="elements" :multi-selection-key-code="['Meta+A']">

<!-- or -->
<VueFlow v-model="elements" :multi-selection-key-code="(event) => event.key === 'Meta'">
```

https://github.com/bcakmakoglu/vue-flow/assets/78412429/5345752a-5be2-4ef2-8094-bcb2ecbcc813

**Comment by bcakmakoglu** [comment]
Can you provide a reproduction for this or at least show some code? Your description is very little to go off and is not producing any errors for me.

**Comment by bUxEE** [comment]
Sorry, my mistake was settings numeric code for Keycode :D

**Comment by bUxEE** [comment]
Sorry, my mistake was settings numeric code for Keycode :D

**Comment by bcakmakoglu** [comment]
@bUxEE 
If you need more control over when the keypress is recognized you can pass a function to the prop.
This function will receive a `KeyboardEvent` as it's argument and is expected to return a `boolean` (is the key pressed or not).
