### ISSUE TITLE
🐛 [BUG]: <title>

### ISSUE THREAD

**Issue by vanexwh** [bcakmakoglu/vue-flow#1327]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

SyntaxError: The requested module '/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js' does not provide an export named 'toValue' (at @vue-flow_core.js?v=8e9793bf:4:160)

### Expected Behavior

When I use vue-flow in uniapp this frame, throw a syntax error. Uniapp frame version is "@dcloudio/uni-h5": "3.0.0-3081220230817001". Please contact me as soon as possible!!!

**Comment by bcakmakoglu** [comment]
Please fill out the bug report properly.
You added no title and the description is almost nothing - how am I supposed to know what you're working with?
What Vue version are you running? 
What version of VueFlow? 
Where does this bug appear? 
Can you provide a reproduction for the issue? 
Anything to help me help you.

Adding "contact me as soon as possible!!!!!!!!!1111oneoneleven" isn't helping either. 
Closing this until the bug report is properly filled out.
