### ISSUE TITLE
🐛 [BUG]: [Vue warn]: Invalid prop name: "ref" is a reserved property. 

### ISSUE THREAD

**Issue by YunYouJun** [bcakmakoglu/vue-flow#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

In new vue@3.4.20, it will throw a warning that `'ref' is a reserved property`.

`BaseEdge` / `CustomEdge` has a prop name `ref`

https://github.com/bcakmakoglu/vue-flow/blob/0f51e2ce24ff1a9be8500925f4fd330d6a62b6cb/packages/core/src/types/edge.ts#L205

![image](https://github.com/bcakmakoglu/vue-flow/assets/25154432/e4c84fa2-ca50-4540-8163-088a65cb40f9)

### Expected Behavior

Remove `ref` props or use another name.

**Comment by bcakmakoglu** [comment]
Thanks for the report - that prop shouldn't be there anymore and will be removed in the next patch 👍

**Comment by bcakmakoglu** [comment]
Fixed with `1.33.2`
