### ISSUE TITLE
🐛 [BUG]: some event Types are missing (nodeClick, nodeDoubleClick, ...)

### ISSUE THREAD

**Issue by delphi-sucks** [bcakmakoglu/vue-flow#1342]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

The published build seems to be missing some event type definitions for Typescript.

The events for `@node-click`, `@node-double-click`, `@node-context-menu`, `@nodes-change`, ... still work like expected, but the types are missing in `VueFlow.vue.d.ts`.

The `edge`-Emits on the other hand work like expected.

### Expected Behavior

The emit types for the mentioned emits should appear within the released build.

### Steps To Reproduce

1. Create a new Vue-Project with `@vue-flow/core`
2. Implement **vue-flow** like in the described in the **Quickstart**
3. Implement `@node-click`
=> Typescript doesn't know the event

### Anything else?

With v1.23.0 it still worked and since v1.24.0 the problem exists.

The `FlowEmits` type within vue-flow's source seems to be correct, but for some reason some events get missing within the type-defintion file `VueFlow.vue.d.ts`.

**Comment by bcakmakoglu** [comment]
Thanks for the report.
Seems like this was introduced with an internal update to Vue 3.3 and vue-tsc 1.8.x, which for some reason produce incorrect definition files.
The edge events seem to overwrite the node events, for whatever reason that is beyond me.

Though there is a solution for this and it will be released with the next patch (`1.33.3`).

**Comment by bcakmakoglu** [comment]
Fixed with `1.33.3`

**Comment by bcakmakoglu** [comment]
Mh... seems like this introduced different warnings now 🤣
I'll reopen this issue to keep track

**Comment by bcakmakoglu** [comment]
Ugh... really?
Yeah it seems to behave like an idiot for some reason and it's super bothersome to check if every event is correctly defined one by one since there's a lot of them ☹️

I'll see if there's more moving around I can do that'll fix it or ask someone in the Vue Discord what the hell is up with this issue.

Will re-open this issue *again* until this is properly sorted out 🥲

**Comment by delphi-sucks** [comment]
Just rechecked on this issue and updated my package of @vue-flow/core from 1.23.0 to 1.37.1 and it seems to work now.

Couldn't find any missing events, so it probably got fixed by a vite update?

**Comment by bcakmakoglu** [comment]
@delphi-sucks might be 😅
I haven't investigated this recently since I'm focusing more on getting prepared for v2
