### ISSUE TITLE
🐛 [BUG]:  Register a custom component for repeated rendering

### ISSUE THREAD

**Issue by NovaAstra** [bcakmakoglu/vue-flow#1349]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Most of my nodes need to be customized and come from the server, so I get the node information loop to register the custom node. At this time, when the node is moved, the responsive dependency makes it register repeatedly, resulting in repeated rendering.

### Expected Behavior

Custom nodes are only rendered once

### Steps To Reproduce

![image](https://github.com/bcakmakoglu/vue-flow/assets/153259141/4f22348a-2b45-499f-bbdd-029221e34e5a)

**Comment by bcakmakoglu** [comment]
This doesn't sound like a VueFlow bug to me but an issue with your implementation that causes excessive re-renders.

Try using the `nodeTypes` object instead: https://vueflow.dev/guide/node.html#node-types-object

**Comment by NovaAstra** [comment]
I see, it's my problem
