### ISSUE TITLE
🐛 [BUG]: Canvas captures scroll even when all scroll-related features are disabled

### ISSUE THREAD

**Issue by snoozbuster** [bcakmakoglu/vue-flow#1360]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When all scroll behaviors are disabled (`pinchToZoom`, `scrollToZoom`, `scrollToPan`), and a canvas is inserted in a scrolling document, scrolling the page such that the pointer enters the canvas boundaries will immediately halt the scroll

### Expected Behavior

Scrolling should not be halted if the scroll event is not used by vue-flow to perform some action

### Steps To Reproduce

1. Disable all scroll-related functionality
2. Scroll the mouse over the canvas

### Anything else?

My thought is that [this code](https://github.com/bcakmakoglu/vue-flow/blob/6b8851bd6778a9ab17190ef17492aca977d91b4f/packages/core/src/container/Viewport/Viewport.vue#L258-L259) should probably only run and "trap" the event if the handler detects that some action should be performed based on the event and current settings. As it stands this issue can be worked around somewhat by adding `nowheel` to the entire canvas, but this only works if it's desired that _all_ events are disabled. if the settings are adjusted so that scroll-to-zoom only happens on cmd/ctrl press, then it's not possible to prevent this issue with `nowheel`.

**Comment by bcakmakoglu** [comment]
Are you possibly just looking for the [`preventScrolling`](https://vueflow.dev/guide/vue-flow/config.html#prevent-scrolling-optional) prop?

**Comment by snoozbuster** [comment]
could be. I wasn't aware of that prop, is it recent? Let me try it out.

**Comment by bcakmakoglu** [comment]
Not really, has existed for more than a year now but isn't really that well documented 😅

**Comment by snoozbuster** [comment]
@bcakmakoglu I don't believe that prop does what I'm looking for. in fact, it doesn't seem to have any effect whatsoever in my app. As a more concrete example, go to https://vueflow.dev/examples/ and add `:zoom-on-scroll="false"` then place the mouse outside the canvas (above or below it) and try to smoothly scroll the page. if you end a scroll with the mouse over the canvas, all further scrolls get eaten by the canvas even though they aren't used. 

In my app, I have a rather thin + wide canvas which is inline on a longer page. so scrolling this page becomes pretty annoying because to a user it seems like their scroll wheel just stops working, since the canvas is stopping all scroll events regardless of whether or not it ends up using them to produce an effect.

**Comment by bcakmakoglu** [comment]
What you describe is exactly the use-case of `preventScrolling`. You need to set it to `false` in order for it to *not* stop scrolling the page when you hit the VueFlow container with a wheel.
It is what's preventing any zoom/pan on scroll when you open vueflow.dev (the top flow with the little buttons to go to different sections of the docs). Otherwise you'd be stuck scrolling in there ^^

**Comment by snoozbuster** [comment]
Ah I see. I was setting it to `true`. But this still doesn't do exactly what I want - it does allow the page to scroll without interference, but it can't be combined with `:zoom-on-scroll="false"` and `zoom-activation-key-code="Ctrl"` in order to have no scroll action by default, but still allow scroll-to-zoom with a modifier. That is what I _really_ want. Is there a way to do that?

**Comment by bcakmakoglu** [comment]
You could track if the `Ctrl` key is pressed and toggle `preventScrolling`.

**Comment by snoozbuster** [comment]
I guess, but my point is why should I have to do that? why is the library calling preventDefault on events it doesn't use? surely that would be a better solution. I would have to duplicate quite a bit of the code inside the library relating to OS detection and key defaulting which is quite fragile.

**Comment by bcakmakoglu** [comment]
I see your point I'm just giving workarounds until it's fixed 😄

**Comment by snoozbuster** [comment]
ah ok 😄 I am ok with waiting for a fix, appreciate it!

**Comment by snoozbuster** [comment]
Ah, I wondered what the hold up was. Is there some counter argument they have? Is the discussion public?

**Comment by bcakmakoglu** [comment]
Not a public discussion no, the hold up is that the devs haven't gotten back to me yet 😅
Pinged recently though I'll ask next week again ^^

**Comment by bcakmakoglu** [comment]
Alright, so the decision about this is that the event should not be caught ^^
Will be fixed in the next patch or minor version (soon)

**Comment by bcakmakoglu** [comment]
I'll be releasing a patch for this issue over the weekend 👍

**Comment by bcakmakoglu** [comment]
Fixed with `1.33.7`
