### ISSUE TITLE
Please setup a discord server for this 

### ISSUE THREAD

**Issue by o1lab** [bcakmakoglu/vue-flow#138]
Nice project. Setting up a discord server will help the community.

Have been trying to get in touch with you over email.

**Comment by bcakmakoglu** [comment]
Hey, thanks for the kind words :)
I was planning on setting up a Discord server but haven't gotten around yet.
If you messaged me via E-Mail it might just be that it got swept under as my Inbox isn't sorted currently and I get a ton of mails 😅
Is there a name to look out for so I can reply to your mail?

**Comment by o1lab** [comment]
@bcakmakoglu : could you please help reach out. Really look forward to it.

**Comment by o1lab** [comment]
Could we please schedule a call :D
