### ISSUE TITLE
🐛 [BUG]: Wrong edge position with dynamic handle id

### ISSUE THREAD

**Issue by romgerman** [bcakmakoglu/vue-flow#1380]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When having a handle like this
```vue
<Handle :id="'0:' + model.type" type="source" :position="Position.Right" />
```
the start position of an edge is wrong
![image](https://github.com/bcakmakoglu/vue-flow/assets/1517367/a07e38ad-8370-491d-8860-01698bae5c1a)

### Expected Behavior

Start position of an edge always in the correct place.

### Steps To Reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-cxekcn?file=src%2Fcomponents%2FTestNode.vue
2. Press "update model"
3. Connect handles
4. Observe incorrect edge position (it's correct if you connect it before updating dynamic id)

### Anything else?

When I make an id of a handle static everything works as expected.

**Comment by romgerman** [comment]
I've added repro on stackblitz.

**Comment by bcakmakoglu** [comment]
You need to call `updateNodeInternals` when you suddenly change the id of an existing handle.
[See this section of the docs about dynamic handles.](https://vueflow.dev/guide/node.html#working-with-dynamic-handle-positions-adding-handles-dynamically)

[Here's the sandbox corrected.](https://stackblitz.com/edit/vitejs-vite-kngfqv?file=src%2Fcomponents%2FTestNode.vue)
```ts
<script setup>
import { Position, Handle, useNode, useVueFlow } from '@vue-flow/core';
import { ref, onMounted, nextTick } from 'vue';

const { updateNodeInternals } = useVueFlow();

const model = ref('test');

function updateModel() {
  model.value = 'test2';
  nextTick(() => {
	// you can also pass an array of ids to specify which nodes in particular to update the internals for
	// when omitted it will update *all* node internals, which might be unnecessary for this case
    updateNodeInternals();
  });
}
</script>

**Comment by romgerman** [comment]
Thank you for the fast answer. I guess I misunderstood the documentation.

**Comment by bcakmakoglu** [comment]
The docs could definitely be better 😅 I am really trying to separate some time to update them but, alas, I have regular work to do as well and it's been taking up all my time recently :(

So always feel free to ask questions / report issues, that's what I'm hear for after all.
