### ISSUE TITLE
🐛 [BUG]: Docs (vueflow.dev) hangs and never loads on iOS Safari

### ISSUE THREAD

**Issue by CodyBontecou** [bcakmakoglu/vue-flow#1387]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Navigating to https://vueflow.dev on safari iOS hangs and eventually crashes, never loading. I've tried vueflow.dev/example and the issue exists there as well.

### Expected Behavior

The website should load.

### Steps To Reproduce

1. iOS 17.5
2. Navigate to https://vueflow.dev on Safari
3. Site never loads.

### Relevant log output

```shell
I attempted to debug this using the Safari inspector, but I'm never able to actually load the site and am instead stuck on Google with the site attempting to load.
```

### Anything else?

This may be a networking issue. Are the docs hosted on Vercel and using a deprecated Node version?

**Comment by bcakmakoglu** [comment]
Works fine for me on Safari, Chrome and FF - doesn't seem to be an actual issue with the docs tbh, more an issue with something on your device (traffic also is very normal, meaning other users can visit the webpage just fine).

**Comment by CodyBontecou** [comment]
Odd, it's loading fine on my device now... not sure what happened there. Sorry about that.
