### ISSUE TITLE
Feature Request: Support for Multiple Handles on Nodes

### ISSUE THREAD

**Issue by frj9641** [bcakmakoglu/vue-flow#1412]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

nodes are limited to having a single input and a single output

### Expected Behavior

Description:

Hello,

I have a feature request regarding the functionality of nodes in Vueflow. Currently, nodes are limited to having a single input and a single output. However, I would like to have nodes with multiple input and output handles. Additionally, I need the flexibility for a single handle to act as both an input and an output.

My specific requirements are:

1.Nodes should support multiple input handles.
2.Nodes should support multiple output handles.
3.A single handle on a node should be able to function as both an input and an output.
Is there any existing implementation that supports these features, or is there a plan to include this functionality in future updates?

Thank you for your attention to this request.

Best regards,

**Comment by bcakmakoglu** [comment]
Nodes are *not* limited to having one handle of each type. Custom nodes can have whatever number of handles you want them to have.

**Comment by frj9641** [comment]
> Nodes are _not_ limited to having one handle of each type. Custom nodes can have whatever number of handles you want them to have. [See this example.](https://github.com/bcakmakoglu/vue-flow/tree/master/examples/vite/src/Unidirectional) Just use the `<Handle>` component and make sure that each Handle gets a unique id and you're good.

I have implemented the code according to the example you provided. However, I found that even if I define multiple source handles, the connection still only starts from the first defined source handle. How should I solve this issue?

**Comment by bcakmakoglu** [comment]
> make sure that each Handle gets a unique id and you're good.

**Comment by frj9641** [comment]
> > make sure that each Handle gets a unique id and you're good.

![image](https://github.com/bcakmakoglu/vue-flow/assets/52986361/3ea621d7-5a37-43c1-9712-6885664b3f67)
![动画1](https://github.com/bcakmakoglu/vue-flow/assets/52986361/38a06f05-74e3-45e9-ba58-e24220354bdd)

I have implemented the code according to the example you provided. However, I found that even if I define multiple source handles, the connection still only starts from the first defined source handle. How should I solve this issue?

**Comment by frj9641** [comment]
> > > make sure that each Handle gets a unique id and you're good.
> 
> ![image](https://private-user-images.githubusercontent.com/52986361/331956442-3ea621d7-5a37-43c1-9712-6885664b3f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY0NDItM2VhNjIxZDctNWEzNy00M2MxLTk3MTItNjg4NTY2NGIzZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYjVjY2Y0OGIwMDIzOWJiZGY2ZDA3OTdlNWVhYWU1MTU2ZGM3NGE4ZDUxNzZiNGJiYWJmNTBlNzgzNzY3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZL1_3eZxJAS4EGUFi7nHCGTo4tCKrkSPPzDi9FkRq4) ![动画1](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ) [ ![动画1](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ) ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ) [ ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> 
> I have implemented the code according to the example you provided. However, I found that even if I define multiple source handles, the connection still only starts from the first defined source handle. How should I solve this issue?

maybe i forget the sourceHandle and targetHandle of edge.

**Comment by frj9641** [comment]
> > > > make sure that each Handle gets a unique id and you're good.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/52986361/331956442-3ea621d7-5a37-43c1-9712-6885664b3f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY0NDItM2VhNjIxZDctNWEzNy00M2MxLTk3MTItNjg4NTY2NGIzZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYjVjY2Y0OGIwMDIzOWJiZGY2ZDA3OTdlNWVhYWU1MTU2ZGM3NGE4ZDUxNzZiNGJiYWJmNTBlNzgzNzY3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZL1_3eZxJAS4EGUFi7nHCGTo4tCKrkSPPzDi9FkRq4) ![动画1](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >       
> >         [
> >           
> >             ![动画1](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >           
> >         ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >         
> >        [ ![动画1](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ) ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >       
> >         [
> >           
> >             ![动画1](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >           
> >         ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/52986361/331956951-38a06f05-74e3-45e9-ba58-e24220354bdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc2NjQsIm5iZiI6MTcxNjE4NzM2NCwicGF0aCI6Ii81Mjk4NjM2MS8zMzE5NTY5NTEtMzhhMDZmMDUtNzRlMy00NWU5LWJhNTgtZTI0MjIwMzU0YmRkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYjcwZDdmNjA5MjM1MzlmMTQ0ODg0OTllYTFhOWQxYTUyNDU4ODk2YzkyNjUzNGVmMzQxOGMwYmJhM2E5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj_RRCW4qhG5Sc3g-jYTCyvsrg7CE34gq1rV0ZxA8sQ)
> > I have implemented the code according to the example you provided. However, I found that even if I define multiple source handles, the connection still only starts from the first defined source handle. How should I solve this issue?
> 
> maybe i forget the sourceHandle and targetHandle of edge.

i solve the problem. thanks

**Comment by frj9641** [comment]
> > make sure that each Handle gets a unique id and you're good.

I forget the sourceHandle and targetHandle of edge. have solved problem. thanks
