### ISSUE TITLE
🐛 [BUG]: Wrong useVueFlow context within pinia

### ISSUE THREAD

**Issue by iyume** [bcakmakoglu/vue-flow#1417]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

**I don't know if this is a bug of vueflow or a limition of pinia.**

When use `useVueFlow` in pinia, it re-create a new instance.

### Expected Behavior

Get same vueflow instance within pinia.

### Steps To Reproduce

`app.vue`:

```vue
<script setup>
import { VueFlow, useVueFlow } from "@vue-flow/core";

const vueFlow = useVueFlow();
console.info("main vue flow", vueFlow.id);

const state = useMyState();
const piniaState = usePiniaState();
</script>

<template>
  <div style="height: 100vh; width: 100vw">
    <VueFlow> </VueFlow>
  </div>
</template>

<style>
@import "@vue-flow/core/dist/style.css";
@import "@vue-flow/core/dist/theme-default.css";
</style>
```

`state.ts`:
```typescript
import { useVueFlow } from "@vue-flow/core";
import { defineStore } from "pinia";

export const useMyState = () => {
  const vueFlow = useVueFlow();
  console.info("in my state", vueFlow.id);
  return useState("myState");
};

export const usePiniaState = defineStore("piniaState", () => {
  const vueFlow = useVueFlow();
  console.info("in pinia", vueFlow.id);
  return {};
});
```

### Relevant log output

```shell
Running the code and get different id:


main vue flow vue-flow-0
in my state vue-flow-0
in pinia vue-flow-1
```

### Anything else?

Environment:
"dependencies": {
  "@pinia/nuxt": "^0.5.1",
  "@vue-flow/core": "^1.33.8",
  "nuxt": "^3.11.2",
  "pinia": "^2.1.7",
  "vue": "^3.4.27",
  "vue-router": "^4.3.2"
}

**Comment by bcakmakoglu** [comment]
Why not just use the state instance generated in pinia and return it from your store?
From what I can tell the problem here is that the pinia doesn't use the same scope as the setup body where `useVueFlow` is called by you, which causes VueFlow to think it needs to create a new state instance.
Instead just call it once in pinia, return the instance and you should be able to use it :)

**Comment by iyume** [comment]
Thanks for your complete reply! I realize that (maybe) both vueflow and pinia create a new effect scope. Sorry I'm not familiar with these advanced scope.
Again, thanks to your reply!
