### ISSUE TITLE
🐛 [BUG]: PanelPositionType not exported

### ISSUE THREAD

**Issue by lasficw** [bcakmakoglu/vue-flow#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

As `PanelPosition` is deprecated we should use the `PanelPositionType`. This type is not exported as of now and can't get imported.

### Expected Behavior

The type `PanelPositionType` should be importable and the minimap and control packages should use the new type instead of the deprecated one.

### Steps To Reproduce

1. Import MiniMap or Control
2. Set position with `position` attribute
3. Editor states that `PanelPosition` is deprecated and that we should use `PanelPositionType` instead

**Comment by bcakmakoglu** [comment]
`PanelPositionType` is simply a string, there's nothing special to export or import here.

```vue
<Panel position="top-left">
 <!-- some content in here -->
</Panel>
```

Not sure what you would want to do with this type anyway? I can add an export to a future release for sure but this isn't a bug either.
