### ISSUE TITLE
🐛 [BUG]: `useHandleConnections` does not call `onConnect` and `onDisconnect`

### ISSUE THREAD

**Issue by ljw20180420** [bcakmakoglu/vue-flow#1423]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

useHandleConnections does not call onConnect when there is a new connection to the handle. Also it does not call onDisConnect when an existing connection is removed from the handle.

### Expected Behavior

useHandleConnections should call onConnect when there is a new connection to the handle. Also it should call onDisConnect when an existing connection is removed from the handle.

### Steps To Reproduce

1. git clone git@github.com:ljw20180420/vueFlowBug.git
2. cd vueFlowBug
3. npm install
4. npm add @vue-flow/core
5. npm run dev
6. access 127.0.0.1:5173
7. remove the edge (select and press backspace), there is not console.log. So onDisConnect is not called.
8. reconnect the two nodes (drag a line between handles), there is not console.log either. So onConnect is not called.

**Comment by bcakmakoglu** [comment]
Good find, thanks for reporting the issue.
Will be fixed with the next patch version.

**Comment by ljw20180420** [comment]
Sorry, I find that I have a typo in "onDisConnect", which should be "onDisconnect". Now onDisconnect works correctly. However, the onConnect still not work correctly.

**Comment by bcakmakoglu** [comment]
Either way I found a bug in the composable 🤣

**Comment by bcakmakoglu** [comment]
Fixed with `1.34.1`
