### ISSUE TITLE
onConnect method in useHandleConnections still not work after update to version 1.34.1

### ISSUE THREAD

**Issue by ljw20180420** [bcakmakoglu/vue-flow#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

onConnect method in useHandleConnections still not work after update to version 1.34.1

### Expected Behavior

onConnect method in useHandleConnections should work after update to version 1.34.1

### Steps To Reproduce

1. git clone https://github.com/ljw20180420/vueFlowBug
2. cd vueFlowBug
3. npm install
4. npm add @vue-flow/core
5. npm run dev
6. Connect the two nodes. There is no console.log display. So onConnect method of useHandleConnections still does not work.

**Comment by bcakmakoglu** [comment]
It works but the existing bug #1393 causes some issues due to auto-generated handle ids.

To solve this set ids on your handles and use the id in `useHandleConnections`
For example:
```vue
<Handle id="left" type="target" :position="Position.Left" />
```

```ts
const conns = useHandleConnections({
  type: 'target',
  id: 'left',
  onConnect(connections) {
    console.log('source connected', connections)
  },
})
```

**Comment by ljw20180420** [comment]
Thank you.
