### ISSUE TITLE
onDisconnect method in useHandleConnections does not work in useHandleConnections if handle id is specified.

### ISSUE THREAD

**Issue by ljw20180420** [bcakmakoglu/vue-flow#1480]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I use handle id in useHandleConnections in order to make onConnect works properly (#1437). However, onDisconnect does not work anymore. If I remove handle id from useHandleConnections, onDisconnect works but onConnect does not work.
```javascript
useHandleConnections({
    type: 'source',
    id: 'source',
    onConnect: (params) => {
        console.log("onConnect", params);
    },
    onDisconnect: (params) => {
        console.log("onDisconnect", params);
    },
});
```

### Expected Behavior

Is it possible to make both onConnect and onDisconnect work?

### Steps To Reproduce

1. git clone https://github.com/ljw20180420/vueFlowBug
2. cd vueFlowBug
3. npm install
4. npm add @vue-flow/core
5. npm run dev
6. Remove the edge by backspace. There is no console.log display. So onDisconnect method of useHandleConnections does not work.

**Comment by bcakmakoglu** [comment]
I can't reproduce this issue.

Given a basic custom node like this:
```vue
<script lang="ts" setup>
import type { CSSProperties } from 'vue'
import type { NodeProps } from '@vue-flow/core'
import { Handle, Position, useHandleConnections } from '@vue-flow/core'

interface Data {
  color: string
  onChange: (event: InputEvent) => void
}

interface ColorSelectorNodeProps extends Pick<NodeProps<Data, {}, 'selectorNode'>, 'data'> {
  data: Data
}

const props = defineProps<ColorSelectorNodeProps>()

useHandleConnections({
  id: 'a',
  type: 'source',
  onConnect(connections) {
    console.log('onConnect', connections)
  },
  onDisconnect(connections) {
    console.log('onDisconnect', connections)
  },
})

const targetHandleStyle: CSSProperties = { background: '#555' }
const sourceHandleStyleA: CSSProperties = { ...targetHandleStyle, top: '10px' }
const sourceHandleStyleB: CSSProperties = { ...targetHandleStyle, bottom: '10px', top: 'auto' }
</script>

<script lang="ts">
export default {
  inheritAttrs: false,
}
</script>

<template>
  <Handle type="target" :position="Position.Left" :style="targetHandleStyle" />

  <div>
    Custom Color Picker Node: <strong>{{ data.color }}</strong>
  </div>

  <input class="nodrag" type="color" :value="data.color" @input="props.data.onChange" />
  <Handle id="a" type="source" :position="Position.Right" :style="sourceHandleStyleA" />
  <Handle id="b" type="source" :position="Position.Right" :style="sourceHandleStyleB" />
</template>
```

both `onConnect` & `onDisconnect` fire as expected when I add or remove an edge from `<Handle id="a" ...>`

Your repo isn't even using a handle id so not sure how that is a meaningful reproduction if it doesn't even replicate the issue you reported.

Closed since I don't think we have a bug here.

**Comment by ljw20180420** [comment]
Sorry, I forget to push my repo. Now there is an id in useHandleConnections. Would you please have a look at my repo? Why does it not work?

**Comment by bcakmakoglu** [comment]
Try upgrading to the latest version.

**Comment by ljw20180420** [comment]
I already have the lateset version 1.36.0.

vueflowbug@0.0.0 /home/XXXXXXXXXXXXXXXXXXXXXX
├── @vitejs/plugin-vue@5.0.5
├── @vue-flow/core@1.36.0
├── vite@5.3.0
└── vue@3.4.27

**Comment by ljw20180420** [comment]
I notice that you use two sources for the node. I also try the node by myself.
```javascript
<script lang="ts" setup>
import { Handle, Position, useHandleConnections } from '@vue-flow/core'

useHandleConnections({
  id: 'a',
  type: 'source',
  onConnect(connections) {
    console.log('onConnect', connections)
  },
  onDisconnect(connections) {
    console.log('onDisconnect', connections)
  },
})

</script>

<script lang="ts">
export default {
  inheritAttrs: false,
}
</script>

<template>
  <span>"node"</span>
  <Handle type="target" :position="Position.Left" />


  <Handle id="a" type="source" :position="Position.Right" />
  <Handle id="b" type="source" :position="Position.Right" />
</template>
```
I delete some rows because vite reports an error:
[vite] Internal server error: [@vue/compiler-sfc] Failed to resolve extends base type
When I remove the edge, the onDisconnect not fire.

By the way, I remove the edge by backspace. Is it the correct way to remove the edge?

**Comment by bcakmakoglu** [comment]
Problem: You are using an edge with *no handle id* - so that edge will not trigger `onDisconnect` since it's not assigned the correct handle id (even though Vue Flow will automatically fall back to that handle, it will not be registered as a connection *to the fallback handle*).

Fix your initial edge definition by adding the appropriate handle ids.

After that it works fine on initial removal and subsequent removals (which already worked fine).

**Comment by ljw20180420** [comment]
It works! Thank you very much.

By the way, https://vueflow.dev/guide/edge.html#edge-props use sourceHandleId and targetHandleId as edge properties. It should be sourceHandle and targetHandle, isn't it?

**Comment by bcakmakoglu** [comment]
No, the props a custom edge receives are named `sourceHandleId` etc.
