### ISSUE TITLE
🐛 [BUG]: Edge arrow is changing its target/source

### ISSUE THREAD

**Issue by jakubmatisak** [bcakmakoglu/vue-flow#1496]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Connecting betwwen custom nodes is changing start/end sides of the edge bewteen them (for me it's visible when it's arrow).
It's random, but after few connections between nodes new edge changes its start/end node.  As you can see in the image also start/end position of the arrow has bad z-index .

Including image (marked in green):
<img width="208" alt="image" src="https://github.com/bcakmakoglu/vue-flow/assets/16204725/97730718-cbc6-4a1d-a6c5-0d3ae18dd524">

### Expected Behavior

Not to change start/end. I didn't find any workaround or something like that.
It was working in  version ^1.33.4, so I had to downgrade. It it not working in any higher version than 1.33.4. 

### Anything else?

This is code of CustomNode.

```
<template>
      <v-card
        color="background"
        elevation="3"
      >
        <v-card-text>
          <v-icon
            class="icon ma-1"
            color="primary"
            size="35"
          >
            mdi-checkbox-outline
          </v-icon>
          {{ label }}
        </v-card-text>
      </v-card>

      <handle
        :position="Position.Top"
        type="target"
      />

      <handle
        :position="Position.Bottom"
        type="source"
      />
</template>
```

**Comment by bcakmakoglu** [comment]
Can you provide a proper reproduction for this issue?

**Comment by bcakmakoglu** [comment]
Tbh I can't reproduce any bugs here.
Maybe it's a misconception with markerEnd and markerStart and where the start and end is.

If you're not defining *all* `<Handle>`  as `type="source"` and using `ConnectionMode.Loose` the handles will be used according to their type (source + target), where the *source* handle will always be the start and the *target* handle always be the end, so the markerEnd would always point to the target handle and not the source.

Other than that (which isn't a bug but intended) I can't see any "problems".

**Comment by jakubmatisak** [comment]
I was debbuging it for last 4 hours. Finally I have found the problem. 
Problem is not with the VueFlow, but it was happening from 1.33.5+.

Solution was kinda stupid, but it was caused by wrapping node and passing in into its child slot. 
After removing one `<div>` it works fine. The fun part is that we didn't changed a thing, except the library version, so I was expecting a bug in vueFlow.

I'm also adding a code:
This is EndNode template
```
<template>
  <node-dialog-wrapper v-bind="props">
    <tooltip-wrapper
      :error="getErrors()"
      :text="getErrors()"
    >
      <v-card
        color="background"
        elevation="3"
      >
        <v-card-text>
          <v-icon
            class="icon ma-1"
            color="primary"
            size="35"
          >
            mdi-circle
          </v-icon>


          {{ label }}
        </v-card-text>
      </v-card>

      <handle
        :position="Position.Top"
        type="target"
      />
    </tooltip-wrapper>
  </node-dialog-wrapper>
</template>
```
and this is TooltipWrapper:
```
<template>
  <div v-if="text?.length > 0">
    <slot />
    <v-tooltip
      activator="parent"
      :class="{'error': error}"
      :close-delay
      :location
      :open-delay
    >
      <template v-if="Array.isArray(text)">
        <div
          v-for="(value, index) in text"
          :key="index"
        >
          {{ $t(value) }}
        </div>
      </template>
      <span v-else>{{ $t(text) }}</span>
    </v-tooltip>
  </div>
  <div v-else>
    <slot />
  </div>
</template>
```
Bug is caused by  `<div v-if="text?.length > 0">` in Tooltip wrapper.
After removing everything except `<slot>` its working fine.

I'm sorry that I was wasting yourr time, but you have to admit it is weird. 
Thank you for your time.

**Comment by bcakmakoglu** [comment]
Interesting, I'll still give it a look, maybe there *is* something there 😄
