### ISSUE TITLE
🐛 [BUG]: Custom Node  input type=number When I click the arrow, the number  will change not stop

### ISSUE THREAD

**Issue by well123** [bcakmakoglu/vue-flow#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I have a custom node. There is an input box in the node. Type is Number. When I click the arrow to change the number, it will not stop
![image](https://github.com/user-attachments/assets/6e156c27-557b-4001-9fbc-f4cdabb9ea5c)

### Expected Behavior

Click the arrow once, the number only increases 1

### Steps To Reproduce

For details, see the picture

**Comment by bcakmakoglu** [comment]
You have to add the `nodrag` class name to the input element.

**Comment by WeiNi-0322** [comment]
I also encountered the same problem when using the Slider component in ElementPlus, but I couldn't solve it by adding the class name "nodrag". Now I don't know what to do.
