### ISSUE TITLE
🐛 [BUG]: applyChanges is not working, but applyDefault does

### ISSUE THREAD

**Issue by fushugaku** [bcakmakoglu/vue-flow#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

in the documentation 
https://vueflow.dev/guide/controlled-flow.html
there is an example of controlled flow that is incorrect

<template>
  <VueFlow :nodes="nodes" :edges="edges" :apply-changes="false" @nodes-change="onNodesChange" />
</template>

there is no prop apply-changes as I can see in the source code, but there is apply-default, that works

### Expected Behavior

Expected to have correct prop in the documentation and replace apply-change to apply-default

**Comment by bcakmakoglu** [comment]
Thanks for the hint, I'll correct the docs on this 👍

**Comment by bcakmakoglu** [comment]
Fixed now.
