### ISSUE TITLE
🐛 [BUG]: useHandle have different type description from official document

### ISSUE THREAD

**Issue by Fnxxxxo** [bcakmakoglu/vue-flow#1601]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Actually, it returns handlePointerDown and handleClick. It also requires different argments.

### Expected Behavior

As document says, useHandle should return onMouseDown and onClick.

### Steps To Reproduce

1. use @vue-flow/core#^1.30.0 or @vue-flow/core#^1.40.0
2. import useHandle and invoke it
3. check returns

### Relevant log output

```shell
public export function useHandle(     {handleId, nodeId, type, isValidConnection, edgeUpdaterType, onEdgeUpdate, onEdgeUpdateEnd}: UseHandleProps):    {handlePointerDown: (event: MouseTouchEvent) => void, handleClick: (event: MouseEvent) => void}
```

**Comment by bcakmakoglu** [comment]
Thanks for the report, docs are updated now to reflect the implementation correctly.
