### ISSUE TITLE
🐛 [BUG]: onNodeClick exectues two times in a row  (Version:1.41.1)

### ISSUE THREAD

**Issue by FinleyCrystal** [bcakmakoglu/vue-flow#1622]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

The function onNodeClick is exectuted twice in a row even though it should be executed once
example:

const editBlock = ref<boolean>(false)

  onNodeClick((params) => {
    editBlock.value = !editBlock.value;
    newLabel.value = params.node.data.label;
    para.value = params.node.id;
    console.log(editBlock.value)
  });

output: 
*click1*
true
false
*click2*
true
false

### Expected Behavior

const editBlock = ref<boolean>(false)

  onNodeClick((params) => {
    editBlock.value = !editBlock.value;
    newLabel.value = params.node.data.label;
    para.value = params.node.id;
    console.log(editBlock.value)
  });

output: 
*click 1*
true
*click2*
false

### Steps To Reproduce

1. create a node
2. create a onNodeClick function
3. let the function output anything
4. execute the onNodeClick function

**Comment by bcakmakoglu** [comment]
Thanks for the report, will be fixed in the next patch.

**Comment by bcakmakoglu** [comment]
Fixed in `1.41.2`
