### ISSUE TITLE
🐛 [BUG]: Strange Issue with zoom and :key="renderKey"

### ISSUE THREAD

**Issue by robinsandstrom** [bcakmakoglu/vue-flow#1637]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Hi, 

I have a strange issue. I fit the nodes like this:

watch(() => renderKey.value, (newVal) => {
  fitView({
    nodes: nodesRef.value.map(obj => obj.id),
    duration: 500,
  })
})

but then whenever I initially scroll, it changes the viewport to the side so only half of the tree is covered. If I remove the :key it works as expected again. Are there any triggers that I'm missing called on the initial scroll? I need the :key because I am using a separate library that calculates all node heights, widths and positions given different settings.

### Expected Behavior

Expected behaviour is that the first scroll event on a new render would behave similarly to all other scroll events and not change the transform of the vue-flow__transformationpane vue-flow__container.

### Steps To Reproduce

Set any <VueFlow> component with a :key, fit the view and scroll. Update the key, fit the view and scroll again.

### Relevant log output

```shell
No logs unfortunately.
```

**Comment by bcakmakoglu** [comment]
Why do you use a key in the first place? 🤔

**Comment by robinsandstrom** [comment]
I need to calculate the sizes for a quite complex tree with some special edges. I do this by first creating all the nodes in Vue-Flow, then I get the sizes of the nodes and then I reassign the positions from the computed tree layout. Without the key I havent been able to get it to update correctly. Can provide code.

**Comment by bcakmakoglu** [comment]
Sounds like a workaround that shouldn't be necessary, a reproduction would be nice so I can get an idea of what you're doing and why it might fail.

**Comment by bcakmakoglu** [comment]
As to your initial question though, the issue you're running into is that you need to reset the state when you change the key.

For example:
```ts
import { ref, nextTick, watch } from 'vue'
import { useVueFlow } from '@vue-flow/core'

const { fitView } = useVueFlow()

const key = ref(0)

watch(key, () => {
  $reset()

  nextTick(() => {
    fitView()
  })
})
```

Although this might result in a slight "jump" - you could hide the flow until the reset is done and unhide it in the `nextTick` callback.

**Comment by robinsandstrom** [comment]
I will try your suggestion, copy some code to my example and if there's a better best practice I'll Try and make a PR to the docs. Thanks for the help! Much appreciated.

**Comment by bcakmakoglu** [comment]
I'm closing this issue for now, if you're still encountering some problems you can still respond in here but I don't see any bug to fix for now ^^
