### ISSUE TITLE
🐛 [BUG]: Selection key code gets reset after switching browser tabs

### ISSUE THREAD

**Issue by alexgrozav** [bcakmakoglu/vue-flow#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When the window gets blurred and focused again, the selection key code `true` value is lost, and the behaviour goes back to panning.

### Expected Behavior

When the window gets blurred and focused again, the selection key code `true` should remain, and selection should be default behaviour instead of panning.

### Steps To Reproduce

Reproduction: https://stackblitz.com/edit/sb1-mhrbpx?file=src%2FApp.vue

1. Set `selection-key-code` to `true`
2. Works as expected
3. Switch browser tabs
4. The behaviour is now back to panning instead of selecting

**Comment by bcakmakoglu** [comment]
Does this issue happen for you in the examples of the next-release? https://vue-flow-docs-git-next-release-burak-cakmakoglus-projects.vercel.app/

I can't seem to reproduce it there anymore.

**Comment by bcakmakoglu** [comment]
Nvm I noticed that this value gets reset once a `blur` or `contextmenu` is event is detected 😄 
Will be fixed in the next release 👍

**Comment by alexgrozav** [comment]
Awesome! Thank you so much 🙏

**Comment by bcakmakoglu** [comment]
Fixed with 1.41.3
