### ISSUE TITLE
🐛 [BUG]: Pan on drag not working when `selectionKeyCode` is set to `true`

### ISSUE THREAD

**Issue by alexgrozav** [bcakmakoglu/vue-flow#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When setting `selectionKeyCode` to `true`, the `panOnDrag` attribute set to `[1]` is not moving the pane using the middle mouse (or any other).

### Expected Behavior

When setting `selectionKeyCode` to `true`, the `panOnDrag` attribute set to `[1]` should be moving the pane using the middle mouse (or any other).

### Steps To Reproduce

1. Set `panOnDrag` to `[1]`
2. Set `selectionKeyCode` to `true`
3. Move pane using middle mouse

Reproduction: https://stackblitz.com/edit/sb1-skrc2f?file=src%2FApp.vue
Relevant code line: https://github.com/bcakmakoglu/vue-flow/blob/a90010b5c47cd1c5236611c8c420189ec3d480dd/packages/core/src/container/Viewport/Viewport.vue#L69

**Comment by bcakmakoglu** [comment]
Thanks for the report. I’ll take a look once I’m back from vacation 👍

**Comment by bcakmakoglu** [comment]
Will be fixed in the next release 👍

**Comment by alexgrozav** [comment]
@bcakmakoglu Thank you! Really appreciate it 🙏

**Comment by bcakmakoglu** [comment]
Fixed with 1.41.3
