### ISSUE TITLE
🐛 [BUG]: Can not use :not() selector in dragHandle

### ISSUE THREAD

**Issue by xunmeng2015** [bcakmakoglu/vue-flow#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Node's props: 
{ id: id, dragHandle: 'div:not(.input-area)' }
It still can drag by div with class 'input-area'

### Expected Behavior

Can not drag by div with class 'input-area'

**Comment by bcakmakoglu** [comment]
The string for drag handle has to be a valid selector for element.querySelector.
Not sure what this issue is supposed to report anyway so im closing it until there’s an actual bug to report here.
