### ISSUE TITLE
🐛 [BUG]: Parent node doesn't expand when coordinates of child node have changed

### ISSUE THREAD

**Issue by antonic901** [bcakmakoglu/vue-flow#1661]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When I change Y coordinate of child node parent node is not shrinking.

### Expected Behavior

When I change Y coordinate of child node parent node should automatically shrink just like when I dragging it using mouse.

### Steps To Reproduce

1. I'm using Quasar Framework
2. I have attached dummy project which demonstrate issue. To run it do the following:

First install packages:
```
npm install
```
then run it:
```
npm run dev
```
and open project on `http://localhost:9000/`

You will notice when using mouse to move child node parent node is automatically shrinking, but when using sliders to update X/Y coordinates of child nodes shrinking doesn't work.

[quasar-project.zip](https://github.com/user-attachments/files/17571731/quasar-project.zip)

**Comment by antonic901** [comment]
I was referring to expanding of parent node when I update child position. Here is video:

https://github.com/user-attachments/assets/db1d4a39-801e-4722-b6cd-2b546d814df5

**Comment by bcakmakoglu** [comment]
This isn't really a bug since `expandParent` is only meant for drag actions and not for programmatic usages.
I'll talk to the XYFlow team if this feature can be extended to cover this case but atm this isn't a bug so I'll close the issue.
If we decide on changing the behavior of this feature I'll let you know ^^
