### ISSUE TITLE
🐛 [BUG]: IsValidConnection is called so many times

### ISSUE THREAD

**Issue by Samir-KH** [bcakmakoglu/vue-flow#1674]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

By adding a console.log() inside the isValidConnection function, we can clearly see that it’s being called multiple times for a single connection attempt. This might become a costly calculation within a complex connection validation logic.

### Expected Behavior

The isValidConnection function is called once, and the result is stored. When the user releases the connection line and attempts to reconnect, the function can be called again at that point.

**Comment by bcakmakoglu** [comment]
This isn't really a bug and issues are *only* for bug tracking here.

You can open up a discussion in the [discussion board](https://github.com/bcakmakoglu/vue-flow/discussions)to suggest potential improvements :)
