### ISSUE TITLE
🐛 [BUG]: Cannot disable moving nodes with Arrow keys

### ISSUE THREAD

**Issue by alexgrozav** [bcakmakoglu/vue-flow#1689]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When pressing Arrow up, left, right, or down, the nodes move and there's no way to configure this.

### Expected Behavior

When pressing Arrow up, left, right, or down, the nodes move only if this feature is enabled. Maybe exporting `arrowKeyDiffs` to be able to change the value of it would help? Or a prop to enable/disable the feature such as `arrowKeysMoveNodes` or similar (default `true`).

### Anything else?

Relevant code:

https://github.com/bcakmakoglu/vue-flow/blob/61f4b0d447fde0eff6324cb7d1f5ae00f9f397bd/packages/core/src/utils/a11y.ts#L10

https://github.com/bcakmakoglu/vue-flow/blob/61f4b0d447fde0eff6324cb7d1f5ae00f9f397bd/packages/core/src/components/Nodes/NodeWrapper.ts#L408

**Comment by bcakmakoglu** [comment]
There is a way to configure this and it's [`disableKeyboardA11y`](https://vueflow.dev/typedocs/interfaces/FlowProps.html#disablekeyboarda11y).

**Comment by bcakmakoglu** [comment]
@alexgrozav Does this solve your issue?

**Comment by bcakmakoglu** [comment]
Closing this issue since there doesn't seem to be any action to take here.
