### ISSUE TITLE
🐛 [BUG]: Background pattern has a slight offset to position 0,0

### ISSUE THREAD

**Issue by delphi-sucks** [bcakmakoglu/vue-flow#1690]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

The Background extension **@vue-flow/background** shows dots, which have a slight offset to the position 0,0.

![2024-11-13_09-11-46_chrome](https://github.com/user-attachments/assets/25eb6098-5fdc-45d8-a1ae-3585de4a706d)

FYI; The _correct_ dots here are made by me and aren't part of the background-extension.

### Expected Behavior

It would be expected, that a dot is exactly at 0,0.

![2024-11-13_09-11-06_chrome](https://github.com/user-attachments/assets/c7c8d917-1fba-474c-9a68-fc1269228a02)

### Steps To Reproduce

1. Setup vue-flow with **@vue-flow/background@1.3.1**
2. add an element at position 0,0
=> the dots have a small offset to the left top corner of the element

### Anything else?

The _bug_ exists since **@vue-flow/background@1.3.1** and it's origin is most likely https://github.com/bcakmakoglu/vue-flow/pull/1666

The PR mentions, that the pattern now starts at 0,0, but I am unsure if this is how it's supposed to be.

When comparing to the main elements container (`class="vue-flow__transformationpane vue-flow__container"`), an offset also exists.

![image](https://github.com/user-attachments/assets/37b6ac4d-cb2d-4ff4-bad7-5c42533cd1c4)

**Comment by bcakmakoglu** [comment]
Thanks, will be fixed in the next patch release 👍

**Comment by bcakmakoglu** [comment]
[@vue-flow/background@1.3.2](https://github.com/bcakmakoglu/vue-flow/releases/tag/%40vue-flow%2Fbackground%401.3.2)
