### ISSUE TITLE
🐛 [BUG]: Moving nodes with Arrow Keys also changes the browser viewport

### ISSUE THREAD

**Issue by delphi-sucks** [bcakmakoglu/vue-flow#1697]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

It's possible to focus/select a node and move it using arrow keys.

When moving a node with the arrow keys, the whole browser viewport also changes.

![2024-11-18_09-35-44_chrome](https://github.com/user-attachments/assets/df695dd0-0a71-45c4-8a86-16fa69c3bdbb)

### Expected Behavior

Changing the position of a node with arrow keys shouldn't effect the browser viewport.

### Steps To Reproduce

1. Create a basic vue-flow environment
2. ensure that your document is bigger than the browser viewport and you need to scroll.
3. Select a node
4. move it towards your scroll direction
=> the node moves and the page scrolls.

This can easily be reproduced using the [Basic example](https://vueflow.dev/examples/).

### Version

Tested with **@vue-flow/core@1.41.5**

### Possible fix?

Most likely an `event.preventDefault();` is just missing.

### Workaround?

There exists the option to disable the arrow keys using [disableKeyboardA11y](https://vueflow.dev/typedocs/interfaces/FlowProps.html#disablekeyboarda11y).

Would it be expected to implement the logic with `preventDefault` for oneself?

**Comment by bcakmakoglu** [comment]
Thanks for the report, this will be fixed in the next patch :)

**Comment by bcakmakoglu** [comment]
Fixed with `1.41.6`
