### ISSUE TITLE
🐛 [BUG]: It seems that labelX and labelY do not make any changes to the Edge component

### ISSUE THREAD

**Issue by danielmoreno510** [bcakmakoglu/vue-flow#1699]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I'm trying to modify the position of the label on a edge by sending labelX and labelY, but I tried with several values ​​and it seems that no change is made,

My code is something like this:  

`[
  {{
      id: 'e1',
      labelX: 100,
      labelY: 10,
      label: 'Test',
      source: 'n1',
      target: 'n2',
      data: { id: 'e1', label: 'Test' },
    }}
]`
  
`<VueFlow :nodes="nodes" :edges="edges">`

![Captura de pantalla 2024-11-28 a las 20 26 11](https://github.com/user-attachments/assets/14669c54-f45b-434e-a470-9ebde47d2a6c)

### Expected Behavior

The label should move in position, but it remains centered on the edge

**Comment by bcakmakoglu** [comment]
`labelX` and `labelY` are not valid properties on an edge object and are not used when rendering the label.
You can use a custom edge if you need to change label positions.

[You can check the edges example for this.](https://vueflow.dev/examples/edges/)
