### ISSUE TITLE
🐛 [BUG]: <title>onConnect method in useHandleConnections does not fire even if handle id is explicitly specified

### ISSUE THREAD

**Issue by ljw20180420** [bcakmakoglu/vue-flow#1712]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

This has been discussed in https://github.com/bcakmakoglu/vue-flow/issues/1480. However, onConnect does not fire now.

### Expected Behavior

onConnect should fire when connect happens.

### Steps To Reproduce

```shell
git clone git@github.com:ljw20180420/vueFlowBug.git
cd vueFlowBug
npm run dev
Delete the initial connection by `backspace`. `onDisconnect` is fired and `console.log` is called.
Try to connect the edge back. `onConnect` is not fired.
```
`onConnect` from `useVueFlow()` works just fine. However, I have several types of nodes. I want to push the `onConnect` logic in the definition file of nodes, so that I do not need to determine node type by `if` or `switch`.

**Comment by bcakmakoglu** [comment]
[Works completely fine for me in a sandbox.](https://codesandbox.io/p/devbox/modest-feather-cg3349?file=%2Fsrc%2FCustomNode.vue%3A9%2C21&workspaceId=ws_7iZPUfEyQC7Podbs7wwbxV)

From what I can tell though you're just misunderstanding `onConnect` of `useHandleConnections`.

```ts
const conns = useHandleConnections({
    type: 'source',
    id: 's',
    onConnect: params => {
        console.log("onConnect", params);
		// You cannot attempt making connections here, this callback is not triggered for connections attempted but connections *made*
        // addEdges([
        //     {
        //         ...params,
        //         type: 'myEdgeType',
        //         updatable: true
        //     }
        // ])
    },
    onDisconnect: params => {
        console.log("onDisconnect", params);
    },
});
```

This is not fired when a connection is *attempted* but is fired when a connection is *made*, meaning the global `onConnect` event is for *attempts* and is fired *before* `onConnect` of `useHandleConnections` triggers, which is only triggered if a new edge is actually created that connects to that handle.
