### ISSUE TITLE
🐛 [BUG]: Misaligned edges after hanles added dynamically 

### ISSUE THREAD

**Issue by JupiterWalker** [bcakmakoglu/vue-flow#1717]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

My custom node will auto-grenerate handles by my props 'conditions' as below:
````
<Handle v-for="(condition, index) in conditions"
            :id="`handle-${condition.id}`"
            :style="{left: `calc((${100 / (conditions.length + 1)}% - 1px) * (${index} + 1))`}"
            type="source" :position="Position.Bottom"
    >
````
    
When I click a button on the page which trigger my func 'onAddCondition' to add a item into condition:
````
const onAddCondition = () => {
  emits('updateNodeInternals')  // not work here

  const newConditionId = `condition-${conditions.value.length + 1}`;
  const newNameId = `name-${conditions.value.length + 1}`;
  conditions.value.push({ id: newConditionId, value: '', nameId: newNameId, name: '' });

  emits('updateNodeInternals')  // not work here neither
};
````

My custon node display the new-added handles well, however, when I connect the handle to other node, the display is wrong:
![image](https://github.com/user-attachments/assets/0f6f8847-78c8-476f-8e96-ec45ad444ae8)

It looks like it just use the position which when I added the hanle but not update after next handle added.

I did see there is a paragrah which introduce how to solve this problem, but the example is too short  to be understand, and I try to use the solution but it doesn't work.

Anyone can help me? 

### Expected Behavior

Expect edge connect handle is right way.
![image](https://github.com/user-attachments/assets/7b9fbe84-caff-4f8b-a711-d9f28b00c856)

**Comment by JupiterWalker** [comment]
After referenced this issue: https://github.com/bcakmakoglu/vue-flow/issues/1380
It works for me after I added `updateNodeInternals();` in the 'hanleOk' function:
`const handleOk = (e) => {

  updateNodeInternals();  // working here
  
  open.value = false;
  const node = findNode(context.currentNodeID)
  nodeInputs.value = []
  conditions.value = []
};`

but I don't understand why not work in 'onAddCondition':
`const onAddCondition = () => {

  const newConditionId = `condition-${conditions.value.length + 1}`;
  const newNameId = `name-${conditions.value.length + 1}`;
  conditions.value.push({ id: newConditionId, value: '', nameId: newNameId, name: '' });
  
  updateNodeInternals();  // not working
};`

![image](https://github.com/user-attachments/assets/f1c0b572-51ac-4365-ad0a-f6d41ba0cc17)

**Comment by bcakmakoglu** [comment]
You need to delay the update node internals calls until handles have been rendered otherwise the call is meaningless.
Try putting it into a next tick or a short set timeout
