### ISSUE TITLE
Conditional adding edges

### ISSUE THREAD

**Issue by insssomniac** [bcakmakoglu/vue-flow#227]
Hello,

I'd like to call addEdges([params]) function conditionaly, if the params is right, but as I see the edge creates regardless of this function call (so i can remove the addEdges() from the code and the new edges still will be created).

Please tell me how I can conditionaly create the new edges ( with nodes it is work: addNodes([newNode]) creates the new node and if the conditions isn't fit, i dont call the addNodes function and node doesn't create )

**Comment by bcakmakoglu** [comment]
Yeah this is a bug with the `auto-connect` prop. It seems to be triggered regardless of setting the prop.

Your first attempt was completely correct, you should add edges using the `addEdges` action.

The bug will be fixed in `v0.4.28`.

**Comment by insssomniac** [comment]
great, thanks!

**Comment by bcakmakoglu** [comment]
@insssomniac `v0.4.28` is out and the fix is in there, let me know if you encounter any more issues :)
