### ISSUE TITLE
Nuxt 3 CJS and ES module - warning

### ISSUE THREAD

**Issue by vvroul** [bcakmakoglu/vue-flow#23]
Hello! 

I'm creating a new Nuxt 3 app using vue-flow and while everything works correctly, I'm getting the below warning (sorry for the low resolution, click to view) :  

![nuxt3-warning](https://user-images.githubusercontent.com/8313366/148803598-bad074bc-824e-43c2-a7b3-8d755d448417.png)

**Comment by bcakmakoglu** [comment]
Thanks for pointing it out - I noticed it too and will be looking at it asap :)

**Comment by bcakmakoglu** [comment]
This got auto-closed with merge - was unintended.
I will leave this open until 0.4.0 is actually released.

**Comment by bcakmakoglu** [comment]
Closed and fixed with #62
