### ISSUE TITLE
 Not working with Nuxt 3

### ISSUE THREAD

**Issue by marcoschwartz** [bcakmakoglu/vue-flow#25]
Hello,

First thanks for your project! It seems amazing and we really want to integrate it as the flow builder for our apps. However we are using Nuxt 3 and I can't find a way to make it work. I tried copying & pasting the minimal example that is in the GitHub main page, as well as the one from the documentation site (Basic.vue), but it just doesn't show anything on the page.

Is there anything specific I have to do to make it work with Nuxt 3? Thanks!

**Comment by bcakmakoglu** [comment]
Hi :)
Can you explain the problem you're having a little more in detail?
What exactly doesn't work? The Documentation of Vue-flow is built with Nuxt3 so it should work as described.

**Comment by marcoschwartz** [comment]
Thanks for the fast answer! I copied exactly the minimal example from the GitHub repo homepage into a nuxt template, actually there are no errors just nothing is showing on the screen. I also added the css files.

**Comment by bcakmakoglu** [comment]
Mh... so does the app not render at all or just the Vue Flow component?
What node version are you using?

there are no errors in the browser console? in the node console? anything to go on would help :D

**Comment by marcoschwartz** [comment]
Just the vue flow part - the rest runs smoothly. And I am using node 17. I ll try some code from the example folder to see if I can see some error at some point :)

**Comment by bcakmakoglu** [comment]
Mh... if you're using the exact same code the only difference that comes to mind is the node version (14 atm but I think i tested it with 16 too) - could you try any of  those versions and see if anything changes?

Could you also try cloning the [docs](https://github.com/bcakmakoglu/vue-flow-docs) and see if that works?

**Comment by marcoschwartz** [comment]
So ... I tried with Node 17, 16 and 14 - no changes at all.

I also tried to change the code I was using (from the homepage of your GitHub repo) to the one you are using in your example (for example it uses v-model instead of elements as an attribute of VueFlow). With that I was finally able to see some warnings:

runtime-core.esm-bundler.js:38 [Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM:   
  at <DraggableCore cancel=".nodrag" handle=undefined disabled=false  ... > 
  at <Node key="1-0" node= Object component= Object  ... > 
  at <Nodes key="node-renderer-vue-flow-0" nodes= Array(2) node-types= Object  ... > 
  at <SelectionPane key="selection-pane-vue-flow-0" edges= Array(1) selected-elements=undefined  ... > 
  at <ZoomPane key="zoom-pane-vue-flow-0" prevent-scrolling=true selection-key-code="Shift"  ... > 
  at <Renderer key="renderer-vue-flow-0" elements= Array(3) > 
  at <VueFlow modelValue= Array(3) onUpdate:modelValue=fn > 
  at <Flow> 
  at <App> 
  at <NuxtRoot>
warn2 @ runtime-core.esm-bundler.js:38
runtime-core.esm-bundler.js:38 [Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <Nodes key="node-renderer-vue-flow-0" nodes= Array(2) node-types= Object  ... > 
  at <SelectionPane key="selection-pane-vue-flow-0" edges= Array(1) selected-elements=undefined  ... > 
  at <ZoomPane key="zoom-pane-vue-flow-0" prevent-scrolling=true selection-key-code="Shift"  ... > 
  at <Renderer key="renderer-vue-flow-0" elements= Array(3) > 
  at <VueFlow modelValue= Array(3) onUpdate:modelValue=fn > 
  at <Flow> 
  at <App> 
  at <NuxtRoot>
warn2 @ runtime-core.esm-bundler.js:38
runtime-core.esm-bundler.js:38 [Vue warn]: Hydration node mismatch:
- Client vnode: g 
- Server rendered DOM:   
  at <Edge key="e1-2-0" edge= Object component= Object  ... > 
  at <Edges key="edge-renderer-vue-flow-0" transform= Array(3) dimensions= Object  ... > 
  at <SelectionPane key="selection-pane-vue-flow-0" edges= Array(1) selected-elements=undefined  ... > 
  at <ZoomPane key="zoom-pane-vue-flow-0" prevent-scrolling=true selection-key-code="Shift"  ... > 
  at <Renderer key="renderer-vue-flow-0" elements= Array(3) > 
  at <VueFlow modelValue= Array(3) onUpdate:modelValue=fn > 
  at <Flow> 
  at <App> 
  at <NuxtRoot>
warn2 @ runtime-core.esm-bundler.js:38
runtime-core.esm-bundler.js:38 [Vue warn]: Hydration children mismatch in <g>: server rendered element contains fewer child nodes than client vdom. 
  at <Edges key="edge-renderer-vue-flow-0" transform= Array(3) dimensions= Object  ... > 
  at <SelectionPane key="selection-pane-vue-flow-0" edges= Array(1) selected-elements=undefined  ... > 
  at <ZoomPane key="zoom-pane-vue-flow-0" prevent-scrolling=true selection-key-code="Shift"  ... > 
  at <Renderer key="renderer-vue-flow-0" elements= Array(3) > 
  at <VueFlow modelValue= Array(3) onUpdate:modelValue=fn > 
  at <Flow> 
  at <App> 
  at <NuxtRoot>

However it still didn't show anything on the page :(

Also as you suggested I tried to reproduce the docs, I got this error when trying to run it:

No "exports" main defined in /Users/marcoschwartz/Documents/Software/tests/vue-flow-docs/node_modules/@nuxt/kit/package.json

**Comment by marcoschwartz** [comment]
Not sure if this can help but I also tested a pure Vue3 version, same issue. I also tested the React library - works like a charm :)

**Comment by marcoschwartz** [comment]
Just managed to make it work - was a CSS files issues after all, so definitely not related to your library. Thanks for the help!

**Comment by bcakmakoglu** [comment]
No problem and glad to hear it resolved itself - the best sort of issue :D

**Comment by ricardosasilva** [comment]
For anyone having the same problem, change the CSS selector from #app to #__nuxt.

**Comment by Eyap53** [comment]
> For anyone having the same problem, change the CSS selector from #app to #__nuxt

Could you elaborate a bit more ? I don't see what I should change

**Comment by khaledOghli** [comment]
it's just worked with me after i make it wrapped with <ClientOnly>

**Comment by l3lackrooz** [comment]
Hello,

I’m currently using the Amazon project on Nuxt.js 3, and it’s been an amazing experience. I hope your problem has been resolved, but I’d like to share a sample of how to use Vue Flow with Nuxt.js.

### 1. Create a Client-Side Plugin

**Create a new file named vueflow.client.ts inside your plugins folder:**

```
├── plugins
 │   └── vueflow.client.ts
```

**Then add the following code to your plugin:**

```
import { defineNuxtPlugin } from '#app'
import { VueFlow } from '@vue-flow/core'
import '@vue-flow/core/dist/style.css'
import '@vue-flow/core/dist/theme-default.css'

export default defineNuxtPlugin((nuxtApp) => {
  // Optionally register VueFlow as a global component
  nuxtApp.vueApp.component('VueFlow', VueFlow)
})
```

### 2. Create a Component or Use It Directly in a Page

- **Define Your Nodes:**

```
const nodes = ref([
  {
    id: 'node-1',
    color: '#ff00ff',
    position: { x: 150, y: 100 },
    label: 'Start Node',
    type: 'default',
    data: { label: 'Start Node' }
  },
  {
    id: 'node-2',
    position: { x: 300, y: 200 },
    label: 'Approval Node',
    type: 'default',
    data: { label: 'Approval Node' }
  },
  {
    id: 'node-3',
    position: { x: 450, y: 100 },
    label: 'End Node',
    type: 'default',
    data: { label: 'End Node' }
  }
])
```

- **Create Your Edges:**

```
const edges = ref([
  { id: 'e1-2', source: 'node-1', target: 'node-2' },
  { id: 'e2-3', source: 'node-2', target: 'node-3' },
])

- **Add Vue Flow to Your Template:**

<template>
  <VCard height="600">
    <VCardText height="600">
      <VueFlow
        :nodes="nodes"
        :edges="edges"
        :vueFlowProps="{ fitView: true }"
        style="width: 100%; height: 500px;"
      />
    </VCardText>
  </VCard>
</template>
```
