### ISSUE TITLE
Snap grid snaps based on starting location

### ISSUE THREAD

**Issue by StefanFabian** [bcakmakoglu/vue-flow#278]
## Expected Behavior
Snap grid should snap all nodes to multiples of the grid resolution.

## Current Behavior
The elements snap but it seems to be based on their starting position, hence, it is possible for two elements to be slightly misaligned.

## Steps to Reproduce

1. In interaction example: https://vueflow.dev/examples/interaction.html
2. Add ` :snap-to-grid="true"` in editor to `VueFlow` element
3. Try to move `Node 2` or `Node 3` to the same `y` as `Node 1`

## Context (Environment)
I think that the main idea of a snap grid is that you can properly align elements because for most people it is mildly annoying if elements are slightly misaligned.

## Possible Implementation
Snap the position to the resolution rather than the delta which is what I assume is done now.

## Thanks
Should also be said: Thank you for working on this project. It's pretty cool, documentation is great and saved me a lot of work!

**Comment by bcakmakoglu** [comment]
Thanks for reporting, I can see the issue 👍

**Comment by bcakmakoglu** [comment]
@StefanFabian Fixed and released with `0.4.40`

**Comment by StefanFabian** [comment]
Nice, thanks for the quick fix! Just tested and works as expected :+1:
