### ISSUE TITLE
Edges are not created if vue-flow is placed in shadow dom

### ISSUE THREAD

**Issue by mspostolov** [bcakmakoglu/vue-flow#280]
Hello!
I found a mistake in the code https://github.com/bcakmakoglu/vue-flow/blob/9ea87c878c327b7d99c75f657ee196172e2862aa/packages/vue-flow/src/utils/graph.ts#L38
It should be `'elementFromPoint'` instead of `'getElementFromPoint'`
`getHostForElement` always returns `window.document` now.

Because of this, edges are not created if vue-flow is placed in shadow dom (vue custom element).

**Comment by bcakmakoglu** [comment]
Thanks for reporting! :)
You're right, I will release a fix asap

**Comment by bcakmakoglu** [comment]
@mspostolov Do you require the fix soon? I could provide a release tomorrow if necessary :)

**Comment by mspostolov** [comment]
It will be great if you release tomorrow. Thanks for the quick fix!

**Comment by bcakmakoglu** [comment]
@mspostolov I might have to defer the release to tomorrow because I would like to fix the snap grid issue as well before publishing - if that takes too long though I will still publish a release with this fix 
Latest will be tomorrow, promise 😄

**Comment by bcakmakoglu** [comment]
@mspostolov Fixed and released with `0.4.40`
