### ISSUE TITLE
When I modify the value of the data of the custom node, then connect the line, an error will be reported.

### ISSUE THREAD

**Issue by LuRM** [bcakmakoglu/vue-flow#288]
Hi! Both my nodes and edges are custom.
When I modify the value of the data of the custom node, then connect the line, an error will be reported. 

<img width="551" alt="image" src="https://user-images.githubusercontent.com/28555984/190572130-54298fcd-005c-4ea8-8628-576c161f2a8c.png">

**Comment by bcakmakoglu** [comment]
Any more information so that I can actually look at the issue?
Code examples? Reproduction?
Anything?

This tells me literally nothing except that you can do screenshots.

**Comment by LuRM** [comment]
I didn't describe it clearly enough. 
```
<vue-flow
      ref="vueFlow"
      @dragover="onDragOver"
      class="vue-flow-container"
      v-model="elements"
      :zoom-on-pinch="false"
      :zoom-on-double-click="false"
      @connect="onConnect"
      style="background: #F5F6FA;"
>
    <!--custom node-->
</vue-flow>
```
Next, I will modify the data of the node.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/28555984/190599300-095f3acf-fa88-4782-bc83-095dacc9a6c6.png">

onConnect
<img width="551" alt="image" src="https://user-images.githubusercontent.com/28555984/190598737-e773da76-ce36-470c-9ccb-c9ae8bf43508.png">

**Comment by bcakmakoglu** [comment]
Are you using the latest version or are you on another one?

**Comment by bcakmakoglu** [comment]
Also is there any more to the error?
Any message that says more than the one's in the screenshot?
Those just indicate that Vue wasn't able to replace an element, which doesn't really tell me why 😄

**Comment by bcakmakoglu** [comment]
Also `edgeType` is not a valid property for edges.
There is only `type` for edges and nodes, so you code should be changed to

```js
const newEdge = {
	id: uuidv4(),
	source,
	target,
	type: edgeType,
	markerEnd: MarkerType.ArrowClosed,
}
```

**Comment by bcakmakoglu** [comment]
Are you possibly using the data to render components in your node? 
It might be that when you "reset" your data obj to `{}` you cause those components to crash due to missing properties?

I tried to emulate your case and didn't receive any errors for it; [Here's a sandbox](https://codesandbox.io/s/festive-cache-301kdz?file=/src/components/ColorSelectorNode.vue)

I would assume that nothing is wrong with VueFlow's behavior and the issue is somewhere in your structure instead.
Vue Flow doesn't really care about your data property anyway, it's just passed through to your components and not handled by the flow at all.

**Comment by LuRM** [comment]
> Also `edgeType` is not a valid property for edges. There is only `type` for edges and nodes, so you code should be changed to
> 
> ```js
> const newEdge = {
> 	id: uuidv4(),
> 	source,
> 	target,
> 	type: edgeType,
> 	markerEnd: MarkerType.ArrowClosed,
> }
> ```

Wrong here, the code is `type`

**Comment by LuRM** [comment]
> <img alt="@LuRM" width="40" height="40" src="https://avatars.githubusercontent.com/u/28555984?s=80&amp;v=4">

Yes. I use data to render the component in my node. But the error content is about flow. I also checked the code, data property are not missing.

**Comment by LuRM** [comment]
> Are you possibly using the data to render components in your node? It might be that when you "reset" your data obj to `{}` you cause those components to crash due to missing properties?
> 
> I tried to emulate your case and didn't receive any errors for it; [Here's a sandbox](https://codesandbox.io/s/festive-cache-301kdz?file=/src/components/ColorSelectorNode.vue)
> 
> I would assume that nothing is wrong with VueFlow's behavior and the issue is somewhere in your structure instead. Vue Flow doesn't really care about your data property anyway, it's just passed through to your components and not handled by the flow at all.

Yes. I use data to render the component in my node. But the error content is about flow. I also checked the code, data property are not missing.

**Comment by LuRM** [comment]
I mean, in my code, I use `type`. `edgeType` here it is written wrong.
I am currently using the latest version. Sorry, here is indeed the vue error.
<img width="948" alt="image" src="https://user-images.githubusercontent.com/28555984/190661001-ea9178c7-1f8e-4161-b03b-561ce566395d.png">
I will try to reproduce in the sandbox.

**Comment by LuRM** [comment]
Hi, I found the reason for the error. Not related to vue-flow, thank you very much for your reply. I will close this issue.
Thank you also for providing such a useful component.
