### ISSUE TITLE
When deleting a node, the neighboring edge deletes

### ISSUE THREAD

**Issue by insssomniac** [bcakmakoglu/vue-flow#291]
Issue tracker is **ONLY** used for reporting bugs.

New features should be discussed in the [discussions](https://github.com/bcakmakoglu/vue-flow/discussions).

# Title
When deleting a node, the neighboring edge deletes also.

## Expected Behavior
When you delete a node -- only edges, connected to it, should be deleted also.

## Current Behavior
When deleting a node, the neighboring edge deletes also, but only visually. When you add new node or change something, it's appearing back.

## Steps to Reproduce

1. Create any type of node. Then create the four nodes below.
2. Create the edges from the first top node to the every bottom node, in order from left to right. So you should have one node on the top and four edges from it to the every bottom node
3. Start deleting bottom nodes, from left to right.
4. You will see what when node deleted, the edge to this node is also deleted (it is normal), but previously created edge from the top node to the neighbour node deletes also, and this is seems a bug.

**Comment by bcakmakoglu** [comment]
Can you add a sandbox as well?
Here's a template:  https://codesandbox.io/s/frosty-minsky-20b0ge

That would be very helpful thank you :)

**Comment by bcakmakoglu** [comment]
Using your instructions doesn't yield the results you describe.
All the edges seem to be deleted properly.

As mentioned, please provide a sandbox reproduction please :)

**Comment by insssomniac** [comment]
For some reason i have an error during running the sandbox, so i just created the repository and recorded the video.
Repo: https://github.com/insssomniac/vue-flow-example , just clone it and run `npm run serve`
Video: https://drive.google.com/file/d/1qvd8SP2lU--ZHR3uxPgONOPWZ3L3q503/view?usp=sharing

**Comment by bcakmakoglu** [comment]
Mh....I am using your repo and can't seem to be able to reproduce the issue as in your video.

https://user-images.githubusercontent.com/78412429/193840265-01a402f7-8446-48da-be56-783f819c4610.mov

Are there any specific logs when the issue appears?
What browser are you using?

**Comment by insssomniac** [comment]
Very strange. I'm on Chrome Version 106.0.5249.61 (Official Build) (64-bit) also tried on Firefox, and had the same issue. Also my colleague faced to the same issue
I recorded again with console opened, maybe it will help
[vue-flow-error-2nd.webm](https://user-images.githubusercontent.com/42058438/193843379-038434dd-96e9-4608-b0d3-d406fcbe442b.webm)

**Comment by bcakmakoglu** [comment]
I can't view the  video you linked, can you link it in a different way? 😄

**Comment by bcakmakoglu** [comment]
Also can you make sure that your browser isn't somehow overwriting the css rule for `.vue-flow__edges`?

It needs to have the overflow rule
```
.vue-flow__edges {
  overflow: visible;
}
```

**Comment by bcakmakoglu** [comment]
@insssomniac 

Replace the following code:

```js
const {
  onNodeDoubleClick,
  onNodeClick,
  onPaneClick,
  onEdgeClick,
  toObject,
  onConnect,
  addNodes,
  addEdges,
  getSelectedNodes,
  applyEdgeChanges,
  applyNodeChanges,
  project
} = useVueFlow()

// ...

onNodeDoubleClick((e) => {
  if (confirm('Delete node?')) {
    applyNodeChanges([{type: 'remove', id: e.node.id}])
  }
})

onEdgeClick((e) => {
  if (confirm('Delete edge?')) {
    applyEdgeChanges([{ type: 'remove', id: e.edge.id }])
  }
})
```

with 

```js
const {
  onNodeDoubleClick,
  onNodeClick,
  onPaneClick,
  onEdgeClick,
  toObject,
  onConnect,
  addNodes,
  addEdges,
  getSelectedNodes,
  removeEdges,
  removeNodes,
  project
} = useVueFlow()

onNodeDoubleClick((e) => {
  if (confirm('Delete node?')) {
		removeNodes([e.node])
  }
})

onEdgeClick((e) => {
  if (confirm('Delete edge?')) {
    removeEdges([e.edge])
  }
})
```

In most cases you should not be using `applyNodeChanges` or `applyEdgeChanges` yourself and if you do then only to intercept the change handlers (for some possible validation for example).
Instead use the appropriate actions for that like `addNodes` or `removeNodes` etc. which will emit these changes through the proper channels and you should not have any issues as seen in the clips.

What happens here is that you remove the node by applying the change yourself, thus Vue Flow never checks if any edges should be removed as well.
After the node gets removed, the edge is seen as "orphaned" and there will be an attempt to remove it.
That apparently doesn't work properly in this case, which I will fix, and instead it removes an edge at another index position.

Anyway, these issues don't appear when you use the actions instead :)

**Comment by insssomniac** [comment]
@bcakmakoglu `removeNodes([e.node])` instead `applyNodeChanges` solved the issue, thanks! 
I don't remeber why i decided to use applyNodeChanges, but i'll replace as you said for nodes and for edges.

**Comment by bcakmakoglu** [comment]
@insssomniac 
With `0.4.41` it should work with applyEdgeChanes as well - you should still use `removeEdges` instead though 😄
