### ISSUE TITLE
[Documentation] Broken links in graph.md

### ISSUE THREAD

**Issue by Modjular** [bcakmakoglu/vue-flow#292]
https://github.com/bcakmakoglu/vue-flow/blob/master/docs/src/guide/utils/graph.md

Most of the header links in the guide are broken.

**Comment by bcakmakoglu** [comment]
@Modjular They're not meant to be accessed through the repo but through the actual docs page :)
The links work fine here: https://vueflow.dev/guide/utils/graph.html

**Comment by Modjular** [comment]
oh lol my bad
