### ISSUE TITLE
Edge g container is cutting connectors

### ISSUE THREAD

**Issue by Dimonka2** [bcakmakoglu/vue-flow#30]
Hi, 
Just found one issue that making connectors pretty unusable.
The SVG group element (with classes .vue-flow__edges .vue-flow__container) is holding all the connectors and has a size of Flow visible area. When the flow diagram is not fitting the screen size nodes are displayed properly, but all connectors are getting cut by initial view frame.
To reproduce it you would need to have two nodes and one connector between them. One node should be located outside of the visible view below. Connector will get cut by the screen view even by panning and zooming.
I hope my explanation is making sense.
Best

**Comment by bcakmakoglu** [comment]
Can you provide a screenshot or something that shows the issue?

**Comment by Dimonka2** [comment]
Hi @bcakmakoglu , sorry I had to take a week off. 
I have this issue in Chromium (Electron). Basically flow contains an svg element with all connectors that has a style `.vue-flow__edges` that contains `overflow: visible;`. And it does not work in Chromium.. I found this bug report about it:
https://bugs.chromium.org/p/chromium/issues/detail?id=231577

**Comment by bcakmakoglu** [comment]
I will take a look - the issue seems to be really old and supposedly fixed so it's strange the behavior still occurs.
It's only affecting Chromium for you? No issues in Firefox or regular Chrome?

**Comment by Dimonka2** [comment]
I haven't tried anything else, but I am using (I believe) the latest Electron. 
So possibly latest Electron does not use the latest Chromium (not sure how to check that)..

On a separate note: `overflow: visible` is grayed out in the devtools of the window, so it seems that even devtools recognizing this behavior as a sort of "feature" of the Chromium. 

Just an idea - maybe it is possible to somehow size this SVG to include area of all connectors and clip view by HTML overflow?

**Comment by bcakmakoglu** [comment]
@Dimonka2 
Interesting idea - I will try and see what I can do and hopefully find a solution to get it working with Electron :)

**Comment by Dimonka2** [comment]
I found a simple fix for my case. Not very universal, but at least working. Adding something like:

```vue
<style>
  vue-flow__container {
    width: 2000px !important;
    height: 2000px !important;
  }
</style>
```
resolving the issue in the area of 2000x2000 what is just enough for me.

**Comment by bcakmakoglu** [comment]
Haven't found a reliable solution yet, so I might patch this in a 0.4.x release as to not delay it further.

**Comment by bcakmakoglu** [comment]
@Dimonka2 Can you possibly try installing `@0.4.7-0.pr92` and see if that version solves works? I would be thankful if you tested it out on your end 😄

**Comment by bcakmakoglu** [comment]
I will close this issue for now - in the long run I hope to find a decent solution for this but currently it doesn't seem as big of an issue as there's not been multiple reports of this (tbf react flow doesn't solve this either)
