### ISSUE TITLE
🐛 [BUG]: Missing type declarations for the new `@vue-flow/additional-components` package

### ISSUE THREAD

**Issue by Modjular** [bcakmakoglu/vue-flow#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When importing any components from `@vue-flow/additional-components` 
```typescript
<script setup lang="ts">
import { VueFlow } from '@vue-flow/core'
import { Background, Controls, ControlButton} from '@vue-flow/additional-components'
```
I get the following Typescript error:

    Cannot find module '@vue-flow/additional-components' or its corresponding type declarations.ts(2307)

### Expected Behavior

I expect no import errors. Also, these are just lint errors; the app still runs fine.
Other note: `@vue-flow/core` does not throw the same error

**Comment by bcakmakoglu** [comment]
Can you provide a reproduction for that? I use the package with TypeScript without having any errors whatsoever.
There are type declarations available (you can check yourself if you want to).

<img width="968" alt="image" src="https://user-images.githubusercontent.com/78412429/195923115-11a92456-d2c0-4022-89f1-e405be54acd9.png">

What does your tsconfig look like? have you tried re-installing node_modules completely and restarting your IDE?
What version are you using?

**Comment by Modjular** [comment]
I feel silly, I don't know why I didn't restart my IDE. No more errors!
