### ISSUE TITLE
panOnScroll not work

### ISSUE THREAD

**Issue by yooki0328** [bcakmakoglu/vue-flow#34]
hi~ Is scroll supported as a move option? 

I run the example code, but it's not work. could you help me?

https://github.com/wbkd/react-flow/issues/1417

**Comment by bcakmakoglu** [comment]
Hello!

`panOnScroll` does work as intended.
You have to activate it using the `zoomActivationKeyCode`.
By default it is set to `Meta`, but if you're for example on Windows it'll be hard to find the "Meta"-Key.
Set it to `Shift` and you should be able to just press Shift + Mouse Scroll to move around the pane.
If you have a mouse with a horizontal wheel (I have a Logitech here that has one) you can also move horiontally.

**Comment by yooki0328** [comment]
> 

```javascript
<VueFlow
                        :model-value="element"
                        :connection-mode="ConnectionMode.Loose"
                        :default-zoom="0.7"
                        :nodes-draggable="false"
                        :zoom-on-scroll="false"
                        :pan-on-scroll="true"
                        zoom-activation-key-code="shift"
                        @load="onLoad"
                    >
                        <Background />
                        <Controls />
                    </VueFlow>
```
when i do a scroll action, but the performance is zoom-in or zoom-out

**Comment by yooki0328** [comment]
I run the InteractionExample, but the performance is also zoom-in or zoom-out.

**Comment by bcakmakoglu** [comment]
It should be `Shift` not `shift` (that's a specc from the browser, not my idea to capitalize the key names 😅)

**Comment by yooki0328** [comment]
> It should be `Shift` not `shift` (that's a specc from the browser, not my idea to capitalize the key names 😅)

Oh~ my fault!

I want to display like this. but it's not work.  https://codesandbox.io/s/xenodochial-yalow-1pgk6
do the scroll action, I want to perform this operation to scroll instead of zoom. 😊

**Comment by bcakmakoglu** [comment]
You mean panOnScroll without having to press a key?
That doesn't work in 0.3.x currently, sorry 😢 
Currently the pan-mode is only working if a key is also pressed (unlike the example you showed where it just activates on scroll).

I can change that for the 0.4.0 release though.

**Comment by yooki0328** [comment]
> You mean panOnScroll without having to press a key? That doesn't work in 0.3.x currently, sorry 😢 Currently the pan-mode is only working if a key is also pressed (unlike the example you showed where it just activates on scroll).
> 
> I can change that for the 0.4.0 release though.

yeah! sometimes panOnScroll means move by scroll. If it's true  and you want to zoom-in or zoom-out, you can specify zoomActivationKeyCode. 
thx very much! Looking forward to version 4.0！😝

**Comment by bcakmakoglu** [comment]
Yeah, I thought of implementing it this way:
`zoomActivationKeyCode` will be `undefined` by default.
If a keyCode is given, it will be mandatory to use said key to activate either zoom or pan/scroll.
If none is given the modes are available without a key.
Disabling the modes would just work by setting `zoomOnScroll` and/or `panOnScroll` to false.

Does that cover your use case?

**Comment by yooki0328** [comment]
> 

Yeah！ The solution can cover my use case! 😬
