### ISSUE TITLE
🐛 [BUG]: Control icons not visible in safari browser

### ISSUE THREAD

**Issue by AlexanderYW** [bcakmakoglu/vue-flow#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Currently icons is hidden in the safari browser but visible in chrome and edge

![Screenshot 2022-10-18 at 13 53 25](https://user-images.githubusercontent.com/4184558/196422295-4c92f5fd-e331-4693-bd28-86fd0ce5a5e0.png)

Safari by default has this css rule provided by the browser
![Screenshot 2022-10-18 at 13 54 09](https://user-images.githubusercontent.com/4184558/196422458-06182186-e8db-479f-9021-f2f66a0fc5a4.png)

The Safari browser believes the icons are size 0 when overflow hidden is applied
![Screenshot 2022-10-18 at 13 56 39](https://user-images.githubusercontent.com/4184558/196422940-5ba7f667-6126-45eb-973c-5cbf7177f8c8.png)

Adding overflow: visible; to the svg enables safari to render the size of the icon
![Screenshot 2022-10-18 at 13 57 16](https://user-images.githubusercontent.com/4184558/196423057-612c4285-4a6a-4d89-a9d8-b46e3d095d59.png)

### Expected Behavior

Control icons are visible in Safari just like in other browsers.

### Anything else?

This is something that broke in between version 0.4.41 and 1.1.3. I migrated my project to the latest version from 0.4.41 today. Didn't notice that you switched npm package name before now :)

**Comment by AlexanderYW** [comment]
This is quite a small bug, but if you feel like it's faster that you look it yourself then go for it, else i might have time to make a PR for this later this week :)

**Comment by bcakmakoglu** [comment]
Thanks for reporting.
As you suggested I opened up a PR with your fix #352 :)

**Comment by bcakmakoglu** [comment]
Fixed with `v1.1.4`

**Comment by AlexanderYW** [comment]
Awesome thanks! 💪
