### ISSUE TITLE
Examples not working on iOS with Safari browser

### ISSUE THREAD

**Issue by ulissepress** [bcakmakoglu/vue-flow#49]
I tried the various  [examples](https://vueflow.dev/examples) using an iPad with Safari and no one is working.
Instead using Google Chrome all is ok.

I also tested the examples in my Mac with Safari and they are fines (i.e. the problems is only with Safari mobile)

**Comment by bcakmakoglu** [comment]
Thanks for reporting.
What kinda of iPad were you using and what version of Safari? 
Can you describe what happens when you visit a page? Does the whole page break or is the flowchart missing?
Maybe also a screenshot? 😄

**Comment by ulissepress** [comment]
I am using an iPad Air (latest iPad OS, 15.4, so same versione for Safari mobile 15.4). 

What happen is that the nodes are rendered, the edges are not, and there is no interaction possibile (nodes cannot be moved and/or selected).

So from the UI point of view you see all the nodes without any edge.

**Comment by bcakmakoglu** [comment]
Might be related to the css issue in #30 but not 100% sure on that.
I will look into it.

**Comment by bcakmakoglu** [comment]
I'll close the issue as stale for now.
If you still experience this, please re-open a new issue with a detailed explanation and possibly error report so I can somehow try to solve the issue, otherwise there's nothing to go on really.
