### ISSUE TITLE
🐛 [BUG]: Custom edge getBezierPath curvature parameter does nothing

### ISSUE THREAD

**Issue by Winston-Guess** [bcakmakoglu/vue-flow#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Changing curvature does absolutely nothing

### Expected Behavior

Changing curvature should adjust the curvature of the Bezier path

### Steps To Reproduce

1. Got to the Vue Flow [Edges custom example](https://vueflow.dev/examples/edges/)
1. replace
`const path = computed(() => getBezierPath(props))`
with 
`const path = computed(() => getBezierPath({...props, curvature: 1}))`
1. notice that nothing happens
1. change the curvature to any other number (e.g. 1000)
1. notice that nothing happens

### Relevant log output

```shell
n/a
```

**Comment by bcakmakoglu** [comment]
Curvature does something but probably not what you think it does :)
Here's what it looks like:

- Curvature 0
<img width="489" alt="image" src="https://user-images.githubusercontent.com/78412429/206394061-e7256627-afda-47ed-8656-b930c2c50094.png">

- Curvature 1
<img width="399" alt="image" src="https://user-images.githubusercontent.com/78412429/206394142-caf61b40-bcb5-480d-9663-d2dab799327c.png">

So curvature influences the curve that an edge has at handles, not the bezier curve itself.

**Comment by Winston-Guess** [comment]
Thanks for the explanation 👍 

Is there a way to edit the bezier curve curvature/elasticity with a few flow function or do I need to create my own / find an external curve creation function?

**Comment by bcakmakoglu** [comment]
Currently, the bezier edge that is provided (+ the `getBezierPath` util) have a fixed curvature to them.
If you want something more custom, you'd have to implement it yourself but I am always open to taking PRs that improve on existing functionality, I just don't have the time right now to work on that as it's not really a highly requested feature 😅
