### ISSUE TITLE
🐛 [BUG]: Handle Slot does not allow for connections to be drawn by element in slot

### ISSUE THREAD

**Issue by bcakmakoglu** [bcakmakoglu/vue-flow#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When you pass an element to the slot, like an svg image or similar, a connection line cannot be drawn from that handle and a full custom handle is necessary.

### Expected Behavior

Slot elements should still allow drawing of connection lines.

**Comment by bcakmakoglu** [comment]
Slots do work if the element inside the slot has either `source` or `target as a class.
Might be nice to be able to omit these classes though and detect the handle differently than how it's done currently, i.e. by checking the source or target class of the "elementBelow".

**Comment by bcakmakoglu** [comment]
Can be handled by setting `pointer-events: none` so no further changes needed in the library.

**Comment by spacekong** [comment]
> Can be handled by setting `pointer-events: none` so no further changes needed in the library.

However, this will cause the elements in the slot to be unable to listen for events, which is not a good solution

Is there any progress in elementBelow

**Comment by 521daichen** [comment]
I have the same problem.
