### ISSUE TITLE
🐛 [BUG]: Connection lines don't start at handles after resizing (Node Resizer)

### ISSUE THREAD

**Issue by Congyuwang** [bcakmakoglu/vue-flow#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Hi, I've tried the new resizer. It now updates the nodes size and position seamlessly. On small problem remains however, the connection line does not start from the handle position, after resizing.
<img width="1470" alt="截圖 2022-12-15 22 02 28" src="https://user-images.githubusercontent.com/52687642/207881349-5ef7ad5a-3151-4128-944f-2e0d68b462f5.png">

### Expected Behavior

I'd expect the connection line to start from the handle, like when it is not yet resized:

<img width="1470" alt="截圖 2022-12-15 22 02 19" src="https://user-images.githubusercontent.com/52687642/207881556-6c3500ef-8572-4399-ba24-48625bbd034e.png">

**Comment by bcakmakoglu** [comment]
Thanks for reporting, I'll look into that :)

**Comment by bcakmakoglu** [comment]
Didn't mean to close this 😄
