### ISSUE TITLE
example DnD.vue  t.drop is not a function

### ISSUE THREAD

**Issue by jscoolso** [bcakmakoglu/vue-flow#56]
drag-n-drop  example 
Chrome browser Drag a node into the panel and an error will be reported in content.js

t.drop is not a function
<img width="445" alt="image" src="https://user-images.githubusercontent.com/52961832/160953249-efe08797-2828-484f-bfaf-d260b610f17c.png">

**Comment by bcakmakoglu** [comment]
Hi and thanks for the report.

Can you provide more information? 
Which version were you using? 0.3.x or the beta?
What is "content.js"? I do not provide any such file.
Are you using a certain ui framework?
Are you using the exact same code as the drag-and-drop example?

**Comment by jscoolso** [comment]
Sorry, error in chrom debug mode, safrai is not wrong, looks like an interference!
