### ISSUE TITLE
🐛 [BUG]: Edges doesn't work on nested nodes

### ISSUE THREAD

**Issue by EvgenyGulyaev** [bcakmakoglu/vue-flow#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

https://vueflow.dev/examples/nodes/nesting.html

I trying use this example. And If I use this example, I don't see edges between nodes in nested nodes 

### Expected Behavior

I want to see edges

### Steps To Reproduce

1 Get example from your documentation and update documentation

### Relevant log output

```shell
None
```

### Anything else?

Thanks for your library

**Comment by bcakmakoglu** [comment]
Please provide a proper reproduction for the issue, otherwise it's hard to know what's wrong.
The link to the example seems to work fine.

**Comment by EvgenyGulyaev** [comment]
Sorry I don't see ... you use rgba for backgroundColor, but if I use rgb I don't see edges

**Comment by bcakmakoglu** [comment]
Ah, I see.
With `1.12.0` edges should be properly grouped by zIndex and that issue should be resolved.
