### ISSUE TITLE
🐛 [BUG]: Snap To Handle example - SnapToHandle.vue component not being garbage collected

### ISSUE THREAD

**Issue by salmasov** [bcakmakoglu/vue-flow#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When there is an `CustomConnectionLine` component passed to VueFlow, it creates new instance of `CustomConnectionLine` component for every new connection, but does not removes old `CustomConnectionLine` component instances

Repository for repro: https://codesandbox.io/p/sandbox/vue-flow-snap-to-handle-garbage-collection-znu6dp

video: 

https://user-images.githubusercontent.com/36544178/216003701-d5fa7495-4bb7-4ff1-8b83-fe323eda71c2.mov

### Expected Behavior

VueFlow creates new instance of `ConnectionLine` for every new connection, and removes old instances

### Steps To Reproduce

1. create `CustomConnectionLine.vue` component with hook subscribed to `onConnectEnd` event. Log component instance uid in that event
2. create connection between nodes
2. delete created connection
3. create another connection between nodes
4. Observe that there is more than on log entry for `onConnectEnd` event
5. repeat steps (2-3) more times
6. Observe that there is on `CustomConnectionLine.vue` component created for every new `ConnectionLine`, and it is still in memory

**Comment by bcakmakoglu** [comment]
I can't reproduce this from what I can tell. Are you using the latest version? 

https://user-images.githubusercontent.com/78412429/216011752-2578c1d9-393e-413a-8544-5e40dc8234fc.mov

**Comment by salmasov** [comment]
I can't reproduce it on the latest version of the library either. Repro was on version 1.12.1. Closing this issue, thanks for pointing out

**Comment by bcakmakoglu** [comment]
@salmasov There's going to be a new release `1.13.0` soon, which will make this example sort of useless anyway, as it will introduce a new option called `connectionRadius` which will allow you to specify a radius at which connection lines will automatically snap to the closest handle.
If you want to have the coloring as seen in the example, you can still use it in combination with the new prop though :)
