### ISSUE TITLE
🐛 [BUG]: Edge mouse over don't work with nested node

### ISSUE THREAD

**Issue by tchiotludo** [bcakmakoglu/vue-flow#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

On nested nodes, edge event is not triggered for edge inside a nested node, see this : 

https://user-images.githubusercontent.com/2064609/216846216-45cb7c6e-0b66-46f1-b4aa-a11e01383da8.mp4

I want to reproduce this behavior but since I use a lot of nested node, I don't know how to handle it without this events triggered: 

https://user-images.githubusercontent.com/2064609/216846327-eb0d7b06-ffa0-4805-8975-d78ff0c209c8.mp4

Additionally, I've rollover that works on node but don't work on edge, see this: 

https://user-images.githubusercontent.com/2064609/216846422-dfaeaf9c-b107-4110-9fdc-825d56676fc0.mp4

The green icon have the same rollover than node and don't work.

### Steps To Reproduce

1. on this [example](https://github.com/bcakmakoglu/vue-flow/blob/develop/examples/vite/src/Nesting/Nesting.vue)
2. add events: 
```js 
const eventTest = () => {
  console.log(arguments)
}

  <VueFlow
    @edge-mouse-enter="eventTest"
    @edge-mouse-move="eventTest"
    @edge-mouse-leave="eventTest"
  >
``` 
3. look at the console, events will be only trigger on the edge that is not nested

### Anything else?

Changing the `vue-flow__edges vue-flow__container` to `z-index: 1` seems to resolved the issue but not sure about the impact

**Comment by bcakmakoglu** [comment]
Technically not a bug as the edges just don't have a z-index by default, which is intended.
You have three options:
1. Set `elevateEdgesOnSelect` to `true` which will automatically set the edges to the z-index of the connected nodes
2. Set a z-index on the edge itself (edge.zIndex)
3. Set a z-index on the edge container (which you tried, that's okay as well).

This behavior might change in the future but currently, it's as is 😄

**Comment by bcakmakoglu** [comment]
Let me know if those options work for you - if not, reopen the issue :)

**Comment by bcakmakoglu** [comment]
You could use `useEdge` for this purpose, which will return the current edge from the context (i.e. if you use it inside a custom edge, it will inject the edge id and fetch the current edge object from the store and return it)

```ts
const { edge } = useEdge()

console.log(edge.sourceNode.computedPosition.z, edge.targetNode.computedPosition.z) // look-up the z position of the connected nodes
```

**Comment by tchiotludo** [comment]
Works perfectly! :tada: 
You are fast man! :clap: 
Thanks a lot :star_struck:
