### ISSUE TITLE
🐛 [BUG]: Examples still use default-zoom which has been replaced by defaultViewport

### ISSUE THREAD

**Issue by rogeru** [bcakmakoglu/vue-flow#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

default-zoom property does not work anymore with latest vueflow version since defaultZoom has be replaced by defaultViewport. Examples should be updated to reflect that change.

### Expected Behavior

Examples should reflect latest version.

**Comment by bcakmakoglu** [comment]
Thanks for reporting, I'll update it 😄
