### ISSUE TITLE
🐛 Custom connection line with Nuxt

### ISSUE THREAD

**Issue by azamat7g** [bcakmakoglu/vue-flow#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Hi! I try to use custom connection line as showed in documentation. I copy example code and try to use with nuxt 3. But connection line is not visible and in console get warning `[Vue warn]: Invalid prop: type check failed for prop "sourceX". Expected Number with value NaN, got Undefined`. 
After that I try to use with vue 3, everything works fine 🤔

Code: https://github.com/azamat7g/vueFlowWithNuxt

### Expected Behavior

It will be fine if on nuxt projects custom connection lines pass source positions as it pass on vue 3 projects

### Relevant log output

```shell
[Vue warn]: Invalid prop: type check failed for prop "sourceX". Expected Number with value NaN, got Undefined  
  at <CustomConnectionLine source-x=undefined source-y=undefined target-x=335  ... > 
  at <RenderFnWithContext key=0 source-x=325 source-y=41  ... > 
  at <ConnectionLine source-node= 
Object { type: "input", dimensions: {…}, handleBounds: {…}, computedPosition: {…}, draggable: undefined, selectable: undefined, connectable: undefined, focusable: undefined, selected: false, dragging: false, … }
 > 
  at <Edges> 
  at <Transform> 
  at <Pane is-selecting=false class="connecting draggable" > 
  at <Viewport> 
  at <VueFlow modelValue= 
Array [ Proxy ]
 onUpdate:modelValue=fn > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: Proxy, <handler>: {…} }
 > > 
  at <RouteProvider key="/" routeProps= 
Object { Component: {…}, route: {…} }
 pageKey="/"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by bcakmakoglu** [comment]
@azamat7g Will be fixed with the next patch `1.14.3`
