### ISSUE TITLE
🐛 [BUG]: Toggling preventScrolling does not fulfill its expected behavior 

### ISSUE THREAD

**Issue by lqbach** [bcakmakoglu/vue-flow#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

[CodeBox example here](https://codesandbox.io/s/tender-orla-fr8wbe?file=/src/App.vue)

According to the [docs](https://vueflow.dev/guide/vue-flow/config.html#prevent-scrolling-optional), setting `prevent-scrolling` to true should prevent the container from scrolling and should instead have the page scroll. In the example above, the page is not able to scroll unless you hover outside the vue-flow container. I am not able to scroll down to Node 5 unless I hover outside the container or manually drag the scrollbar.

### Expected Behavior

If `prevent-scrolling` is true, you should be able to hover anywhere on the page and have the default page scroll functionality.

### Steps To Reproduce

1. [CodeBox example](https://codesandbox.io/s/tender-orla-fr8wbe?file=/src/App.vue)
2. Attempt to scroll inside container (this should fail)
3. Attempt to scroll outside container, hovering over the scrollbar (this should work)

**Comment by bcakmakoglu** [comment]
`preventScrolling` needs to be set to `false` in order to achieve what you expect (the default is `true`, which will allow scrolling inside the viewport to zoom/pan).
If it's `false` you will instead scroll the whole page and not zoom/pan in the viewport.

**Comment by bcakmakoglu** [comment]
Though I just noticed the docs saying the opposite, I will change that 😄

**Comment by lqbach** [comment]
Gotcha, thanks for the quick reply! It's working as expected now 👍
