### ISSUE TITLE
🐛 [BUG]: Can't show/hide handle during connection process. 

### ISSUE THREAD

**Issue by heaven-born** [bcakmakoglu/vue-flow#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When I start a connection, even if I hide (display:none) handle div visually, the functionality of the handle remains active on the screen and I observe a visual "magnetic connection" effect. Vue-flow can only disable when the connection is completed or canceled. 

### Expected Behavior

When the handle is hidden its functionality must disappear immediately even during the connection process. Except maybe for the source handle involved in the current connection.

### Steps To Reproduce

1. create two nodes: one node with a source handle and another node with a target handle
2. Create a code that hides (display:none) the target handle div after the connection is started on the source handle. For example:

``` 
 watch(
      connectionStartHandle,
      (pre, post) => {
            targetHandleReactiveStyle.display='none'
       }
)
```

3. Observe that the "magnetic" functionality is still working on the location where the handle is not displayed anymore. 
4. Cancel the connection and start it one more time. Now the "magnetic" function finally disappears.

**Comment by bcakmakoglu** [comment]
You really shouldn't use css to "hide" the handle if you want to avoid connecting to it. CSS is not considered when looking for the closest handle available, it will just look for an element within the radius.

Instead use a `v-if` to actually remove the handle from the DOM, which will prevent "magic connection" as you call it ^^

**Comment by heaven-born** [comment]
got it. Thanks! Closing this bug then.

**Comment by heaven-born** [comment]
hm. looks like 'v-if' doesn't fix the issue.  so I'm reopening.

**Comment by bcakmakoglu** [comment]
Can you provide a sandbox reproduction for this issue? :)

**Comment by bcakmakoglu** [comment]
[Here's a basic template.](https://codesandbox.io/p/sandbox/vue-flow-basic-gfgro4)
It would make it easier to debug if I had a sandbox reproducing this issue 😅

**Comment by bcakmakoglu** [comment]
https://user-images.githubusercontent.com/78412429/222098810-4d7d4f91-4ccb-4c5d-b1ca-5dbf3adf603d.mov

`v-if` seems to solve the issue for me.

```vue

const handleVisible = ref(true)

watch(connectionStartHandle, () => {
  handleVisible.value = !connectionStartHandle.value
})


<Handle v-if="handleVisible" type="target" :position="Position.Left" :style="targetHandleStyle" />

**Comment by heaven-born** [comment]
you are right. I have the same behavior in my sandbox as you have in yours. Maybe something is different in my local env. Need to investigate it.  For now, I'm closing the bug.

**Comment by heaven-born** [comment]
I've finally reproduced the issue. It is not exactly what I initially described, but very close it in.
Here is the sandbox:  https://codesandbox.io/p/sandbox/vue-flow-bug-reporduce-jpekby

When you start the connection from the bottom handle, you will not be able to connect to the top handle right after they appear. Buy on the second try you can.

**Comment by bcakmakoglu** [comment]
Mh... you shouldn't pop-in handles when trying to create a connection as the handles are looked up on pointerDown and not pointerMove, meaning, Vue Flow has no knowledge of this handle potentially existing when the connection is started (pointerDown = connectStart). 
I might change this behavior at a later point or offer another event like `beforeConnectStart`, which could be used to pop the handle in before a connection is even started.

Though for now you can achieve the same effect using `opacity: 0` and `opacity: 100` instead.

**Comment by heaven-born** [comment]
That was my first idea actually, but because there I have two overlapping source and target handles and there is also a bug with the overlapping handles, opacity doesn't work for me.

Here is the bug reproduction: https://codesandbox.io/p/sandbox/vue-flow-bug-reporduce-forked-8ccfn5

You can't connect to the target even if it is located on top of the source handle by z-index.

**Comment by bcakmakoglu** [comment]
Yeah, because z-index is irrelevant for checking the closest handles. If they're on top of each other, Vue Flow can't determine which is the correct handle and will use one, and in this case possibly the wrong one.
That's not really a good solution either to place two handles on top of one another.
What even is the use-case for this? ^^

Why not just use `ConnectionMode.Loose` and use a single handle typed as `source` and that's it?

**Comment by heaven-born** [comment]
That's because the target handle is custom elements that contain custom content, and the source is just a regular handler. I centered both of them in my node and wanted to show the target handler on top of the whole node content in order to reflect that this node is ready to accept the connection, and when it is connected, I wanted to hide it behind the node again. 
It is just my attempt to implement floating edges with both handles located in the center of the node. 

I will go with the `ConnectionMode.Loose` then.  It just looked to me that separating the handles by type is a bit easier in the implementation.

**Comment by bcakmakoglu** [comment]
Mh... I'm not sure I properly understand, though wouldn't a single handle where you hide the custom content depending on connection status work?

Something like this?
```vue
<Handle>
   <div v-if="someCondition">...</div>
</Handle>
```

**Comment by heaven-born** [comment]
yeah, this will work. I've only been working with vue/TypeScript/vueflow for about 3 weeks, so some of my design solutions may seem weird :)

**Comment by bcakmakoglu** [comment]
I see, no worries 😄 

I'll consider using z-index as well when looking up handles for connections as well, maybe this case has some usages for others as well.

**Comment by bcakmakoglu** [comment]
@heaven-born Were you able to solve your issue or is there something that blocks you still?

**Comment by heaven-born** [comment]
@bcakmakoglu I've found some workaround using one handle. btw, it would be nice to be able to change the handle during connection with `connectionStartHandle.value.handleId = newId`. Now it works only visually and I can't get the new handle in listeners when the connection is finished.

**Comment by bcakmakoglu** [comment]
@heaven-born 
Is there anything you would need from the library to get your solution working? Otherwise this issue will be closed 😄
