### ISSUE TITLE
🐛 [BUG]: Drag & Drop as child of node

### ISSUE THREAD

**Issue by jacksonsilvadev** [bcakmakoglu/vue-flow#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I am trying to make a node that contains a container that can be sorted, but I cannot get the click to adapt to the VueDraggable container, it always takes the reference from the node.

I have tried setting pointer-events to none and also elementSelectable to false, but without success

https://user-images.githubusercontent.com/43053055/227233707-6b098086-7f46-495d-be16-bc82a5784714.mp4

### Expected Behavior

https://user-images.githubusercontent.com/43053055/227233727-c9a0bb97-b03f-4ff1-abdd-0f80d8f039a2.mp4

### Anything else?

VueDraggableNext: https://github.com/SortableJS/vue.draggable.next

**Comment by bcakmakoglu** [comment]
Have you added the `nodrag` class name to your container?
Without this class name the mouse events will always be caught by the vue flow node.

**Comment by jacksonsilvadev** [comment]
This worked here, Thanks bro!
