### ISSUE TITLE
drag-n-drop doesn't seem to work

### ISSUE THREAD

**Issue by poerlang** [bcakmakoglu/vue-flow#8]
https://vueflow.dev/examples/drag-n-drop

![11](https://user-images.githubusercontent.com/3243514/143399795-7ae5edc8-b752-4379-9920-4e392ee90b9f.gif)

drag-n-drop doesn't seem to work

**Comment by bcakmakoglu** [comment]
Thanks, I will check it out

**Comment by bcakmakoglu** [comment]
@poerlang 
Fixed in Versions ^0.2.x - You can check it out on the [example page](https://vueflow.dev/examples/drag-n-drop)
