### ISSUE TITLE
🐛 [BUG]: snap target on the connection edge and the actual target for edge rendering don't match

### ISSUE THREAD

**Issue by snoozbuster** [bcakmakoglu/vue-flow#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When dragging an edge to a handle, the snap target for the connection edge places the line target at the dead center of the handle. However, once that edge is released, the edge is actually drawn with the target at the top center of the handle. This isn't super noticeable with the default settings (small handles, no `markerEnd`) but it becomes very noticeable when using a larger handle size (eg `15x15`) and end markers. 

### Expected Behavior

The connection line should match exactly with the final drawn edge.

### Anything else?

I imagine the connection line is the thing that would have to budge to match the final edge, because the edge can't be drawn over the top of the handle due to updatable edges and multi-connected handles. If this is an acceptable solution, I'm happy to open a quick PR (my belief is that this is a one-line change in ConnectionLine.vue).

**Comment by bcakmakoglu** [comment]
This is not really a bug, the connection line, by default, just has a higher z-index than default edges and nodes and therefore is shown on top. If you want to have it below the nodes and therefore the handles you can just use some css
```css
.vue-flow__connectionline {
  z-index: 0;
}
```

**Comment by snoozbuster** [comment]
no, I'm not referring to z-index (at least, I don't think so). Take a look at this gif:

![snap](https://user-images.githubusercontent.com/5778364/229222542-53f6ebaf-fb01-4ec8-acdd-6fcb3031f53a.gif)

When the connection line snaps to the handle, the tip of the arrow is in the dead center of the handle. When I let go, it snaps up to the top of the handle. It should be consistent, no?
