### ISSUE TITLE
🐛 [BUG]: Handle with `connectable: 'single'` can have multiple connections if connected in reverse in Strict mode

### ISSUE THREAD

**Issue by snoozbuster** [bcakmakoglu/vue-flow#823]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

In this [codesandbox](https://codesandbox.io/p/sandbox/hungry-rumple-i4ecmk?file=%2Fsrc%2FApp.vue), there are four custom nodes (nodes 2-5). `Node 1` is a `connectable: false` node that comes with a pre-existing connection to node 2. All the custom nodes have a `connectable: 'single'` output handle and a `connectable: true` input handle. 

If you connect node 3 to node 1 by drawing an edge from its input to node 1's output, the edge is created, even though the node (and handle) are not connectable. 

### Expected Behavior

The `single` option should be considered when creating an edge in any direction. The above interaction should not create an edge.

### Anything else?

In my project, I thought I was also able to reproduce this behavior in general by drawing an edge from a `connectable: true` input to a `connectable: 'single'` output. However, I can't reproduce this in the example I shared - the bug seems to require the source handle to be `connectable: false`.

**Comment by bcakmakoglu** [comment]
Btw your codesandbox is outdated - the `latest` vue-flow package shouldn't work with `additional components` package 😄 

[Use this one instead.](https://codesandbox.io/p/sandbox/vue-flow-basic-gfgro4?file=%2Fpackage.json)

Though the reported issue is also in the latest version.
