### ISSUE TITLE
🐛 [BUG]: <Handle /> connectable prop default should true

### ISSUE THREAD

**Issue by ZhengZhouXu** [bcakmakoglu/vue-flow#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Handle can't connect，because connectable default is false. But I upgraded from 1.15.2 to 1.18.1，they're not compatible.

### Expected Behavior

<Handle /> connectable prop default should true

**Comment by bcakmakoglu** [comment]
Mh... this would cause a different issue though, as a handle will use `nodesConnectable` if `connectable` is undefined.
Though I did notice that handles have `connectable` as `false` as their default, which isn't the intended default. The intended default value is `undefined` which would cause a handle to fall back to the global `nodesConnectable` value, which is `true` by default.

**Comment by tisha077** [comment]
Please, describe it in the documentation that in order for custom nodes to work correctly, when setting the Handle, you must put `connectable="true"` to be able to connect.
Thanks

**Comment by bcakmakoglu** [comment]
@tisha077 It's not gonna be required in `1.18.2`, this is just an issue because `connectable` currently falls back to `false` instead of `undefined` (see my previous comment)

**Comment by bcakmakoglu** [comment]
Fixed with `1.18.2`, please update and let me know if you still experience issues :)

**Comment by tisha077** [comment]
@bcakmakoglu works correctly, thanks!
