### ISSUE TITLE
🐛 [BUG]: <title>找不到模块“@vue-flow/core/dist”或其相应的类型声明。

### ISSUE THREAD

**Issue by HMS-0908** [bcakmakoglu/vue-flow#866]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and this is a new bug.

### Current Behavior

import fail typesscript error

### Expected Behavior

pnpm install ,import error can not find types

**Comment by HMS-0908** [comment]
null

**Comment by bcakmakoglu** [comment]
I don't speak Chinese, could you please elaborate your problem in English properly? 😄

**Comment by bcakmakoglu** [comment]
Reopen the issue if necessary with a proper description, thank you
