### ISSUE TITLE
🐛 [BUG]: Tailwind @apply dark:<xxx> doesn't work after updating

### ISSUE THREAD

**Issue by remiconnesson** [bcakmakoglu/vue-flow#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I'm using a bunch of tailwind `@apply` to stylize the graph in various scenario

for example:

```
:deep(.vue-flow__node){
  @apply cursor-pointer font-mono bg-slate-100 dark:text-slate-100 dark:bg-slate-700
}

:deep(.vue-flow__edge path) {
  @apply dark:stroke-cyan-900
}

:deep(.vue-flow__handle) {
  @apply dark:bg-slate-700 dark:border-slate-900
}


:deep(.vue-flow__controls-button){
  @apply dark:bg-slate-700 dark:border-slate-800
}

:deep(.vue-flow__controls-button svg){
  @apply dark:stroke-slate-300
}

```

and it was working fine with the following deps
```
    "@vue-flow/controls": "^1.0.0",
    "@vue-flow/core": "^1.11.1",
    "@vue-flow/minimap": "^1.0.1",
```

but now with versions
```
      "@vue-flow/controls": "^1.0.5",
      "@vue-flow/core": "^1.19.0",
      "@vue-flow/minimap": "^1.1.1",
```
the dark styles don't apply.

I tried several version of tailwind with both vue-flow v1.11 and vue-flow and the problem is not occuring with vue-flow 1.11 but is with the latest version

I have no idea what could be causing this 

The styles applied without the dark modifier does work so tailwind is able to reach, it is just the dark version that are not working.

### Expected Behavior

dark styles applied with @apply are working again

### Steps To Reproduce

(I'm going to try to build a minimal repro later on)

**Comment by bcakmakoglu** [comment]
Can you create a sandbox reproduction for this? Off the cuff I can't tell you what's going wrong 😄 
[Here's a template.](https://codesandbox.io/s/github/bcakmakoglu/vue-flow/tree/master/examples/vite/src/Basic)

**Comment by bcakmakoglu** [comment]
No worries, any reproduction would be helpful, the template is just to make it easier to get started ^^

**Comment by remiconnesson** [comment]
here is the repro https://github.com/remiconnesson/minimal-repro-vueflow-tw-apply

**Comment by remiconnesson** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/28846642/232450457-d0efdf59-247d-4776-ba8d-6089030127dd.png">

the nodes should turn red in dark mode
<img width="665" alt="image" src="https://user-images.githubusercontent.com/28846642/232450569-01bb94f1-50fe-4ff5-ae6d-801af27fb999.png">

but they don't

<img width="630" alt="image" src="https://user-images.githubusercontent.com/28846642/232450652-549846fd-3de0-433a-93e8-e7f1a463f92a.png">

**Comment by bcakmakoglu** [comment]
Doesn't work for me in `1.11.1` either, but it does work if you remove the `scoped` modifier from your style tag and just use simple css

```css
.vue-flow__node {
  @apply cursor-pointer bg-green-100 dark:text-red-100 dark:bg-red-700;
}

**Comment by bcakmakoglu** [comment]
Tbf this doesn't look like a Vue Flow issue but somewhat of an issue with dark mode styles not being properly applied to elements selected with `:deep` - nothing I can do about it honestly.

For example this isn't working either.
```vue
<template>
	<div class="barbaz">
		<Foobar />
	</div>
</template>

<style scoped>
.barbaz :deep(.foobar) {
  @apply text-xl text-red-500 dark:text-white;
}
```

```vue
// Foobar.vue
<template>
	<div class="foobar">Foo</div>
</template>
```

But this works completely fine

```css
.barbaz .foobar {
  @apply text-xl text-red-500 dark:text-white;
}
```

So the issue here doesn't seem like it's related to Vue Flow at all.

**Comment by remiconnesson** [comment]
Oh thank you very much

I will update my code without scoping in the meantime and I will try to isolate which deps is causing this and open an issue in the correct repo

Sorry for the mistake

**Comment by remiconnesson** [comment]
FYI the issue seems to come from `tailwindcss@3.3` ,

After experimenting with different versions of the deps, I tried to put `tailwind@3.2` against `tailwind@3.3` and `3.2` works fine with `:deep(...) { @apply dark:<xxx>` but `3.3` doesn't

https://github.com/remiconnesson/tailwind-vue-deep-apply-dark-bug

**Comment by remiconnesson** [comment]
FYI the issue seems to come from `tailwindcss@3.3` ,

After experimenting with different versions of the deps, I tried to put `tailwind@3.2` against `tailwind@3.3` and `3.2` works fine with `:deep(...) { @apply dark:<xxx>` but `3.3` doesn't

https://github.com/remiconnesson/tailwind-vue-deep-apply-dark-bug

**Comment by bcakmakoglu** [comment]
Good to know 😄 
I usually use UnoCSS instead of Tailwind so I haven't noticed this problem previously but it might be good to open an issue with them to make them aware of this problem
