### ISSUE TITLE
🐛 [BUG]:  Weird behaviour of input type="number" inside a node

### ISSUE THREAD

**Issue by Ch4mpl00** [bcakmakoglu/vue-flow#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

There is a weird behaviour of `<input type="number">` inside a node:
When click on native input increment/decrement button is starts increment value continuously instead of one time increment.
Moreover, on hover on increment/decrement control it affects it's value.

**Example**

https://user-images.githubusercontent.com/62772443/233582660-8ec025d3-d9bb-4c41-8d50-76f647ae8dd1.mov

**Code**

```vue
<template>
  <div style="padding: 30px; background: white">
    <Handle id="input" type="target" position="top" />
    <input v-model="selectedDiscount" type="number" />
  </div>
</template>

<script setup>
  const selectedDiscount = ref(0)
</script>

```

### Expected Behavior

Click on native control of input should cause just 1 time increment/decrement

**Comment by bcakmakoglu** [comment]
Can you provide a reproduction for this issue?
I used the code you provided in [a sandbox](https://codesandbox.io/p/sandbox/holy-hill-gbd18h?file=%2Fsrc%2FApp.vue) and it works completely fine.

**Comment by Ch4mpl00** [comment]
> 

Hmm, here is a video from your sandbox and here is the same bug. (Tried on different computers)

https://user-images.githubusercontent.com/62772443/233587873-32accff8-fe33-449d-aa10-affa237d44ac.mov

**Comment by bcakmakoglu** [comment]
What browser are you using? 🤔

**Comment by bcakmakoglu** [comment]
Your touchpad isn't the culprit, it's a chrome related issue.
Though you can fix it by adding `class="nodrag"` to your input element

```html
    <input v-model="selectedDiscount" class="nodrag" type="number" />
```

**Comment by Ch4mpl00** [comment]
Oh I see, true that it's Chrome issue. Checked in FireFox and it works ok. Thx a lot!

**Comment by iyume** [comment]
Can this be fixed on chrome (without nodrag)?
