### ISSUE TITLE
🐛 [BUG]: Deleting a node that has a connected edge that has `deletable: false` will always trigger an orphaned edge error

### ISSUE THREAD

**Issue by snoozbuster** [bcakmakoglu/vue-flow#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

See title. When deleting a node that has any connected edges that are `deletable: false`, an orphaned edge error is always logged. In my environment, the edge is not removed from the state and every future modification to the graph re-triggers an error on the same edge (although I was not able to create a repro for this). 

### Expected Behavior

No orphaned edge error is logged, as the edge is not rendered and effectively does not exist/was deleted anyway.

### Steps To Reproduce

1. Hook `onError` to `console.error`
2. Make any edge in the [Basic example](https://vueflow.dev/examples/) `deletable: false`
3. Delete the associated edge
4. An orphaned edge error is logged

### Anything else?

The fact that nodes/edges which are `deletable: false` aren't deletable when calling `deleteX()` manually has tripped me up before, but I never logged a bug/issue for it because it seemed intentional and was consistent, even though my natural instinct is that the flag would only control whether or not the user is able to delete the node via the `deleteKeyCode`. However, the fact that the library itself tries to respect this flag when performing its own internal cleanup seems broken to me and in at least this case, it produces an invalid internal state. (Similar behavior also exists if a node has a `parentNode` and is `deletable: false` - the child node is not deleted and left orphaned when the parent node is deleted. But, no error is logged, so I never opened a bug for that either.)

**Comment by bcakmakoglu** [comment]
Mh… I’ll take a look and see what can be done about this. Thanks for another in-depth report :)

**Comment by snoozbuster** [comment]
Thanks! I figure this will be kinda tricky to solve because everything is using the same utilities, and I imagine there's some concerns around breaking changes as well. I'm in no hurry for this though, I found a workaround in my application for the time being.

**Comment by bcakmakoglu** [comment]
Should be fixed with `1.19.3`
