### ISSUE TITLE
🐛 [BUG]: deleting a node during a drag throws an unhandled error

### ISSUE THREAD

**Issue by snoozbuster** [bcakmakoglu/vue-flow#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

If you delete a node using backspace during a drag operation, there will be a "cannot read properties of undefined (reading "id")" error within the library.

### Expected Behavior

No error is tracked

### Steps To Reproduce

0. In the [basic example](https://vueflow.dev/examples/), wire up `console.error` to the `@error` event
1. Click a node in the Basic example to select it
2. Start dragging that node
3. While dragging, press Backspace to delete
4. Error is logged

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at vue-flow-core.mjs:1239:31
    at Array.find (<anonymous>)
    at Sn (vue-flow-core.mjs:1239:17)
    at A (vue-flow-core.mjs:2258:22)
    at HTMLDivElement.<anonymous> (vue-flow-core.mjs:2310:195)
    at Rt.call (vue-flow-core.mjs:1456:18)
    at Object.R [as mouse] (vue-flow-core.mjs:2206:11)
    at f (vue-flow-core.mjs:2157:7)
    at vue-flow-core.mjs:1940:7
```

**Comment by bcakmakoglu** [comment]
Thanks for the report, will be fixed with `1.19.3`
