### ISSUE TITLE
🐛 [BUG]: Edges connected to hidden nodes do not get hidden

### ISSUE THREAD

**Issue by domvie** [bcakmakoglu/vue-flow#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When hiding nodes, connected edges do not get hidden. Version 1.19.4

### Expected Behavior

According to the documentation, edges connected to hidden nodes will automatically be hidden: https://vueflow.dev/examples/hidden.html

### Steps To Reproduce

Simply try hiding a node with edges or try the official example in the docs: https://vueflow.dev/examples/hidden.html

**Comment by bcakmakoglu** [comment]
Thanks for reporting - this will be fixed in `1.20.0`
