### ISSUE TITLE
🐛 [BUG]: Connection radius of  'disabled' handles cancels section of connection radius of 'connectable' handles. 

### ISSUE THREAD

**Issue by heaven-born** [bcakmakoglu/vue-flow#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

The connection radius area of the active handle is reduced near the disabled handle.  

### Expected Behavior

The disabled handle should not affect the active handle.

### Steps To Reproduce

Example:

https://codesandbox.io/p/sandbox/unruffled-sound-0s0pcj?file=%2Fsrc%2FApp.vue%3A26%2C34

1. Start connection from the target node to the source node.
2. You will notice that the bottom handle on the source node is disabled (as expected), but the connection radius of the top handle is reduced on the side of the bottom handle. 

It looks like the connection radius of the disabled handle cancels part of the connection radius of the active handle.

**Comment by bcakmakoglu** [comment]
Can you describe the issue more clearly, please?
1. A radius of 80 seems silly and unnecessary
2. None of the handles in your sandbox are "disabled" so I'm not sure what you're referring to.

**Comment by heaven-born** [comment]
For this specific example, radius 80 doesn't make much sense. This is just for demonstration purposes. 

Regarding 'disabled' handles. When I say 'disabled' I mean it is not supposed to accept connections. 

The bottom handler of the "source"  node is disabled by `is-valid-connection` in the target node. It means that I will not be able to start the connection from the "target" node and connect to the bottom handle of the "source" node. And this part is working as expected. However, if you check the "magnetic" effect (connection radius) around the top handler of the "source" node you will notice that this circle is not distributed evenly around the handle. This is because the bottom handler overlaps the radius of the top handle and somehow makes the radius of the top handle smaller on the bottom handle side.

**Comment by bcakmakoglu** [comment]
Fixed with `1.20.1`
