### ISSUE TITLE
Why first node position always located at (0,0), whatever I initialize it?

### ISSUE THREAD

**Issue by terry8yu** [bcakmakoglu/vue-flow#96]
I found two issues:
1. When I put several nodes and edges into two array separately, and assign them to :nodes and :edges, also gave the nodes init position values, but the first (also the root) node is always located at (0,0), not the value I gave (340, 20);
![location-bug](https://user-images.githubusercontent.com/13606514/164179452-800cfba5-abbe-408b-85cd-2d414524a177.png)
2. If some of the edges are not visible(out of canvas) after the first init, they will keep invisible all the time even I drag them into canvas.
![edges-bug](https://user-images.githubusercontent.com/13606514/164179419-2a7cac8a-943e-4888-9944-ecd7128b929b.png)

When I just gave the init position value(0, 0) to the first node , I found the second issue.

**Comment by bcakmakoglu** [comment]
Hi, thanks for reporting!

What version are you using? What Browser were you testing this with?

I can't seem to reproduce the first issue, can you maybe create a minimal reproduction?
Here's a [sandbox](https://codesandbox.io/s/jovial-wave-ww09ir?file=/src/components/Basic.vue) where I try to emulate your case.

You assign some initial nodes and edges and pass them to vue flow using the `:nodes="initialNodes"` `:edges="initialEdges"` props, am I understanding you correct?

The second issue might be related to #30 - are you by any chance using Chromium? 
Can you provide a reproduction here too?

I'll gladly look into the issue more 😄

**Comment by bcakmakoglu** [comment]
I have a fix for the overflow issue, which I can push into a pre-release so you could test it out if you'd like.

**Comment by terry8yu** [comment]
Thanks, I can't reproduce the first issue in the sandbox, but I just re-assign the init value(not the same, re-assign the same value doesn't work) to the first node after the decoding node-data from a file, it works now. Do twice reassign can get what I want. 
For the second issue I will try ur new update, Thanks!!

**Comment by bcakmakoglu** [comment]
@terry8yu Can you maybe give me a code example of the decoding?
Just a basic overview of what you do roughly so I can try and re-create it for future cases.

**Comment by bcakmakoglu** [comment]
@terry8yu Can you try installing the `@0.4.7-0.pr92` version and see if that version solves the edge overflow issue? 😄 I would be thankful if you tested it out on your end.

**Comment by bcakmakoglu** [comment]
I'll close the issue for now.
If you got any more issues, please open a new one
