### ISSUE TITLE
🐛 [BUG]: Invert style does not work on Safari

### ISSUE THREAD

**Issue by atyshka** [bcakmakoglu/vue-flow#970]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Inverted-color edges do no appear in Safari, but work in Chrome. This is strange because the invert filter has been supported for many years in Safari.
<img width="485" alt="Screen Shot 2023-06-02 at 9 33 41 AM" src="https://github.com/bcakmakoglu/vue-flow/assets/19317207/a31451f6-4f48-40a5-966c-8f6a8f6ebfb4">

### Expected Behavior

Edges should appear as they do in Chrome.
<img width="398" alt="Screen Shot 2023-06-02 at 9 34 09 AM" src="https://github.com/bcakmakoglu/vue-flow/assets/19317207/06c539f5-6965-4f42-b619-d0edbe03ce7d">

### Steps To Reproduce

Open this page in Safari (I'm using desktop 16.4.1)
https://vueflow.dev/examples/nodes/

**Comment by Lehoczky-peakfs** [comment]
This is a knows webkit bug: https://bugs.webkit.org/show_bug.cgi?id=261806
