### ISSUE TITLE
🐛 [BUG]: Vue-flow seems to be broken after build with vite

### ISSUE THREAD

**Issue by franck-gautier** [bcakmakoglu/vue-flow#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When the application is running with "vite" on dev everything works fine 
But when i'm trying to build and preview , i have several errors raised into the browser console : 

`Error: <pattern> attribute x: Expected length, "NaN".
index-205f4b3e.js:7493 Error: <pattern> attribute x: Expected length, "NaN".
patchAttr @ index-205f4b3e.js:7493
index-205f4b3e.js:7493 Error: <pattern> attribute x: Expected length, "NaN".
patchAttr @ index-205f4b3e.js:7493
index-205f4b3e.js:7493 Error: <pattern> attribute x: Expected length, "NaN".
patchAttr @ index-205f4b3e.js:7493
[..]`

Seems to be related to generate SVG whiches missing some props values 
![Capture d’écran 2023-06-05 à 20 25 23](https://github.com/bcakmakoglu/vue-flow/assets/118285919/7ab2ddc1-2768-4169-8c76-b71a5abf80dd)

I use Background , Minimap , Controls  
I cannot find a way to solve that and btw deploy the application on production 

### Expected Behavior

After a build i can use Vue-flow like it ran in dev mode

### Steps To Reproduce

Install vite fresh app 
Create a vue flow using composition API 
Use plugins Background, Minimap , Controls
Build and run preview mode

**Comment by bcakmakoglu** [comment]
You'll have to provide a proper reproduction for this as I can personally confirm that it works in production using Vite with the latest version 😄

**Comment by bcakmakoglu** [comment]
You can actually just use this repo as an example.

- Go into `/examples/vite`
- Run `vite build`
- Run `vite preview`

<img width="1722" alt="image" src="https://github.com/bcakmakoglu/vue-flow/assets/78412429/8640cc5a-aa47-41b3-950b-0ceac124cfc9">

**Comment by franck-gautier** [comment]
Thank you for your quick reply , i had the same configuration but i'm not using Typescript , i finally found one difference : 

into the main js file i didn't have `app.config.performance = true` after adding it works !!
