### ISSUE TITLE
🐛 [BUG]: Custom Edge component is reinitialized on z-index change

### ISSUE THREAD

**Issue by heaven-born** [bcakmakoglu/vue-flow#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Custom Edge re-initializes its reactive state on z-index change.

Probably this is also an issue for changes in the 'data' field, but I'm not sure because I can't reproduce it anymore.

### Expected Behavior

I expect that the state remains stable. 

### Steps To Reproduce

https://codesandbox.io/p/sandbox/tender-kare-unfy3k?file=%2Fsrc%2FApp.vue%3A30%2C30

1. Click on the Edge. You will see the label value that represents the state will be changed. 
2. Clicking the "Change edge z-index" button resulting the state reset to the initial value.

**Comment by bcakmakoglu** [comment]
What's the problem here?
You have conflicting descriptions, the Issue title mentions Custom *Nodes*, the description talks about Custom *Edges*.
Aside from that the issue doesn't even specify what the exact problem is.
"Re-initializes" tells me basically nothing. What do you mean exactly?

**Comment by heaven-born** [comment]
sorry, it's all about the custom edge. I fixed the title. 

>>Aside from that the issue doesn't even specify what the exact problem is.

See the steps to reproduce, I provided an example in a sandbox. "Re-initializes" means "resets". I'm not very good at the terminology.

**Comment by bcakmakoglu** [comment]
Fixed with `1.20.2`
