### ISSUE TITLE
🐛 [BUG]: Allow to disable default selection click event processing on edge

### ISSUE THREAD

**Issue by heaven-born** [bcakmakoglu/vue-flow#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I'm not sure if this is a bug or a design choice, so let me explain the issue.
 
On the backend, my nodes and edges are stored in separate tables and have a separate set of IDs. I use these IDs as the IDs for my elements in a `vueflow` graph without adding any extra namespace prefix\prefx. This leads to the situation when I have duplicated IDs in my elements.   And this is not a problem in most cases, because when I use `vueflow` API I explicitly tell what kind of element I want to work with (`findNode`, `findEdge` etc..).  But in some rare cases, the IDs interfere with each other.

See this Sanbox example: 
  https://codesandbox.io/p/sandbox/gallant-thunder-8jvcvl?file=%2Fsrc%2FApp.vue%3A20%2C21

When I click on `Edge`, it automatically selects a `Node` with the same IDs. However, if I programmatically do something like `edge.selected=true` (not provided in the example), it doesn't select the node. 

So my question: is this designed and correct behavior? If yes, can I disable this default click functionality on `Edge`? If I disable the default functionality, I can implement it manually using `edge.selected=true` that doesn't select the node with the same ID. 

### Expected Behavior

Not sure. I would prefer a separate namespace for IDs for different element types. 

### Steps To Reproduce

Sandbox:  https://codesandbox.io/p/sandbox/gallant-thunder-8jvcvl?file=%2Fsrc%2FApp.vue%3A20%2C21

Click on the `Edge` and observe that the `Node` with the same ID becomes selected as well.

**Comment by bcakmakoglu** [comment]
Why would you use duplicate ids?
Whatever you do, an id is supposed to be a *unique identifier* and *not duplicate* regardless of element type.

This is technically not a bug but a mis-use on your end.
What happens is, that the edge gets selected, which triggers a change event to happen, which will toggle the selected flag on the element with the specific id that was selected and seeing as you're using duplicate ids, multiple elements are toggled.

Again: *Don't duplicate ids. Ever. Stop doing that* 😄

**Comment by bcakmakoglu** [comment]
*No duplicate ids*, sorry ^^
