### ISSUE TITLE
🐛 [BUG]: Animated edge has dashed selection area

### ISSUE THREAD

**Issue by heaven-born** [bcakmakoglu/vue-flow#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When 'animated=true' property is set on an edge, the edge becomes dashed. Along with the dashed appearance, the selection area also becomes dashed. By 'selection area' I mean the area where a regular 'grab' cursor becomes a 'pointer' cursor.  When I move my mouse pointer along the animated edge the cursor is alternating between these two states. 

### Expected Behavior

The 'selection area' must not be dashed. 

### Steps To Reproduce

1. Go to the https://vueflow.dev/
2. Move the cursor along the dashed edge.

**Comment by bcakmakoglu** [comment]
Fixed with `1.20.2`
