### ISSUE TITLE
🐛 [BUG]: <title>The styles on the official website seem to be completely out of order

### ISSUE THREAD

**Issue by shengalways** [bcakmakoglu/vue-flow#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

The styles on the official website seem to be out of order

### Expected Behavior

The styles on the official website can return to normal

**Comment by bcakmakoglu** [comment]
can you be more specific? What styles are not correct?
When I check on multiple browsers and my phone everything looks completely normal.

A screenshot or a proper description would help, until then the task will be closed for a lack of information
